// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID         int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID *int32  `gorm:"column:employee_id;type:int unsigned;index:employee,priority:1" json:"employee_id"`
	Username   *string `gorm:"column:username;type:varchar(255)" json:"username"`
	Password   *string `gorm:"column:password;type:varchar(255)" json:"password"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
