// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID           int32   `gorm:"column:id;type:int;primaryKey" json:"id"`
	CompanyName  *string `gorm:"column:company_name;type:varchar(255)" json:"company_name"`
	ContactName  *string `gorm:"column:contact_name;type:varchar(255)" json:"contact_name"`
	ContactTitle *string `gorm:"column:contact_title;type:varchar(255)" json:"contact_title"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
