// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameEmployee = "employee"

// Employee mapped from table <employee>
type Employee struct {
	ID             int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	EmployeeNumber *string `gorm:"column:employee_number;type:varchar(255)" json:"employee_number"`
	Name           *string `gorm:"column:name;type:varchar(255)" json:"name"`
	Department     *string `gorm:"column:department;type:varchar(255)" json:"department"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
