// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameProcessEdge = "general.process_edge"

// ProcessEdge mapped from table <general.process_edge>
type ProcessEdge struct {
	ID            int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProcessID     *int32  `gorm:"column:process_id;type:int unsigned" json:"process_id"`
	ProcessName   *string `gorm:"column:process_name;type:varchar(255)" json:"process_name"`
	Type          *string `gorm:"column:type;type:varchar(255)" json:"type"`
	StartNodeNum  *int32  `gorm:"column:start_node_num;type:int unsigned" json:"start_node_num"`
	StartNodeName *string `gorm:"column:start_node_name;type:varchar(255)" json:"start_node_name"`
	EndNodeNum    *int32  `gorm:"column:end_node_num;type:int unsigned" json:"end_node_num"`
	EndNodeName   *string `gorm:"column:end_node_name;type:varchar(255)" json:"end_node_name"`
	ConditionExpr *string `gorm:"column:condition_expr;type:varchar(255)" json:"condition_expr"`
}

// TableName ProcessEdge's table name
func (*ProcessEdge) TableName() string {
	return TableNameProcessEdge
}
