// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameItem = "item"

// Item mapped from table <item>
type Item struct {
	ID       int32   `gorm:"column:id;type:int;primaryKey" json:"id"`
	ItemCode *string `gorm:"column:item_code;type:varchar(255)" json:"item_code"`
	Name     *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
