// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameProcess = "process"

// Process mapped from table <process>
type Process struct {
	ID   int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName Process's table name
func (*Process) TableName() string {
	return TableNameProcess
}
