// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameProcessNode = "process_node"

// ProcessNode mapped from table <process_node>
type ProcessNode struct {
	ID        int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProcessID *int32  `gorm:"column:process_id;type:int unsigned;index:process,priority:1" json:"process_id"`
	Name      *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName ProcessNode's table name
func (*ProcessNode) TableName() string {
	return TableNameProcessNode
}
