// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

const TableNameTableRegistry = "table_registry"

// TableRegistry mapped from table <table_registry>
type TableRegistry struct {
	ID           int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	TableName_   *string `gorm:"column:table_name;type:varchar(255)" json:"table_name"`
	DatabaseName *string `gorm:"column:database_name;type:varchar(255)" json:"database_name"`
}

// TableName TableRegistry's table name
func (*TableRegistry) TableName() string {
	return TableNameTableRegistry
}
