// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/dao/model"
)

func newQuoteEmployee(db *gorm.DB, opts ...gen.DOOption) quoteEmployee {
	_quoteEmployee := quoteEmployee{}

	_quoteEmployee.quoteEmployeeDo.UseDB(db, opts...)
	_quoteEmployee.quoteEmployeeDo.UseModel(&model.QuoteEmployee{})

	tableName := _quoteEmployee.quoteEmployeeDo.TableName()
	_quoteEmployee.ALL = field.NewAsterisk(tableName)
	_quoteEmployee.ID = field.NewInt32(tableName, "id")
	_quoteEmployee.EmployeeID = field.NewInt32(tableName, "employee_id")

	_quoteEmployee.fillFieldMap()

	return _quoteEmployee
}

type quoteEmployee struct {
	quoteEmployeeDo

	ALL        field.Asterisk
	ID         field.Int32
	EmployeeID field.Int32

	fieldMap map[string]field.Expr
}

func (q quoteEmployee) Table(newTableName string) *quoteEmployee {
	q.quoteEmployeeDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quoteEmployee) As(alias string) *quoteEmployee {
	q.quoteEmployeeDo.DO = *(q.quoteEmployeeDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quoteEmployee) updateTableName(table string) *quoteEmployee {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.EmployeeID = field.NewInt32(table, "employee_id")

	q.fillFieldMap()

	return q
}

func (q *quoteEmployee) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quoteEmployee) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 2)
	q.fieldMap["id"] = q.ID
	q.fieldMap["employee_id"] = q.EmployeeID
}

func (q quoteEmployee) clone(db *gorm.DB) quoteEmployee {
	q.quoteEmployeeDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quoteEmployee) replaceDB(db *gorm.DB) quoteEmployee {
	q.quoteEmployeeDo.ReplaceDB(db)
	return q
}

type quoteEmployeeDo struct{ gen.DO }

type IQuoteEmployeeDo interface {
	gen.SubQuery
	Debug() IQuoteEmployeeDo
	WithContext(ctx context.Context) IQuoteEmployeeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuoteEmployeeDo
	WriteDB() IQuoteEmployeeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuoteEmployeeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuoteEmployeeDo
	Not(conds ...gen.Condition) IQuoteEmployeeDo
	Or(conds ...gen.Condition) IQuoteEmployeeDo
	Select(conds ...field.Expr) IQuoteEmployeeDo
	Where(conds ...gen.Condition) IQuoteEmployeeDo
	Order(conds ...field.Expr) IQuoteEmployeeDo
	Distinct(cols ...field.Expr) IQuoteEmployeeDo
	Omit(cols ...field.Expr) IQuoteEmployeeDo
	Join(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo
	Group(cols ...field.Expr) IQuoteEmployeeDo
	Having(conds ...gen.Condition) IQuoteEmployeeDo
	Limit(limit int) IQuoteEmployeeDo
	Offset(offset int) IQuoteEmployeeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteEmployeeDo
	Unscoped() IQuoteEmployeeDo
	Create(values ...*model.QuoteEmployee) error
	CreateInBatches(values []*model.QuoteEmployee, batchSize int) error
	Save(values ...*model.QuoteEmployee) error
	First() (*model.QuoteEmployee, error)
	Take() (*model.QuoteEmployee, error)
	Last() (*model.QuoteEmployee, error)
	Find() ([]*model.QuoteEmployee, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuoteEmployee, err error)
	FindInBatches(result *[]*model.QuoteEmployee, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QuoteEmployee) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuoteEmployeeDo
	Assign(attrs ...field.AssignExpr) IQuoteEmployeeDo
	Joins(fields ...field.RelationField) IQuoteEmployeeDo
	Preload(fields ...field.RelationField) IQuoteEmployeeDo
	FirstOrInit() (*model.QuoteEmployee, error)
	FirstOrCreate() (*model.QuoteEmployee, error)
	FindByPage(offset int, limit int) (result []*model.QuoteEmployee, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuoteEmployeeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quoteEmployeeDo) Debug() IQuoteEmployeeDo {
	return q.withDO(q.DO.Debug())
}

func (q quoteEmployeeDo) WithContext(ctx context.Context) IQuoteEmployeeDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quoteEmployeeDo) ReadDB() IQuoteEmployeeDo {
	return q.Clauses(dbresolver.Read)
}

func (q quoteEmployeeDo) WriteDB() IQuoteEmployeeDo {
	return q.Clauses(dbresolver.Write)
}

func (q quoteEmployeeDo) Session(config *gorm.Session) IQuoteEmployeeDo {
	return q.withDO(q.DO.Session(config))
}

func (q quoteEmployeeDo) Clauses(conds ...clause.Expression) IQuoteEmployeeDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quoteEmployeeDo) Returning(value interface{}, columns ...string) IQuoteEmployeeDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quoteEmployeeDo) Not(conds ...gen.Condition) IQuoteEmployeeDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quoteEmployeeDo) Or(conds ...gen.Condition) IQuoteEmployeeDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quoteEmployeeDo) Select(conds ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quoteEmployeeDo) Where(conds ...gen.Condition) IQuoteEmployeeDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quoteEmployeeDo) Order(conds ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quoteEmployeeDo) Distinct(cols ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quoteEmployeeDo) Omit(cols ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quoteEmployeeDo) Join(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quoteEmployeeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quoteEmployeeDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quoteEmployeeDo) Group(cols ...field.Expr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quoteEmployeeDo) Having(conds ...gen.Condition) IQuoteEmployeeDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quoteEmployeeDo) Limit(limit int) IQuoteEmployeeDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quoteEmployeeDo) Offset(offset int) IQuoteEmployeeDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quoteEmployeeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteEmployeeDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quoteEmployeeDo) Unscoped() IQuoteEmployeeDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quoteEmployeeDo) Create(values ...*model.QuoteEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quoteEmployeeDo) CreateInBatches(values []*model.QuoteEmployee, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quoteEmployeeDo) Save(values ...*model.QuoteEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quoteEmployeeDo) First() (*model.QuoteEmployee, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuoteEmployee), nil
	}
}

func (q quoteEmployeeDo) Take() (*model.QuoteEmployee, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuoteEmployee), nil
	}
}

func (q quoteEmployeeDo) Last() (*model.QuoteEmployee, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuoteEmployee), nil
	}
}

func (q quoteEmployeeDo) Find() ([]*model.QuoteEmployee, error) {
	result, err := q.DO.Find()
	return result.([]*model.QuoteEmployee), err
}

func (q quoteEmployeeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuoteEmployee, err error) {
	buf := make([]*model.QuoteEmployee, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quoteEmployeeDo) FindInBatches(result *[]*model.QuoteEmployee, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quoteEmployeeDo) Attrs(attrs ...field.AssignExpr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quoteEmployeeDo) Assign(attrs ...field.AssignExpr) IQuoteEmployeeDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quoteEmployeeDo) Joins(fields ...field.RelationField) IQuoteEmployeeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quoteEmployeeDo) Preload(fields ...field.RelationField) IQuoteEmployeeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quoteEmployeeDo) FirstOrInit() (*model.QuoteEmployee, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuoteEmployee), nil
	}
}

func (q quoteEmployeeDo) FirstOrCreate() (*model.QuoteEmployee, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuoteEmployee), nil
	}
}

func (q quoteEmployeeDo) FindByPage(offset int, limit int) (result []*model.QuoteEmployee, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quoteEmployeeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quoteEmployeeDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quoteEmployeeDo) Delete(models ...*model.QuoteEmployee) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quoteEmployeeDo) withDO(do gen.Dao) *quoteEmployeeDo {
	q.DO = *do.(*gen.DO)
	return q
}
