import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// 配置文件路径：对应后端的 Go 文件以及前端生成的 TS 文件
const GO_MODELS = [
  {
    name: 'Account',
    filePath: path.resolve(__dirname, '../../backend/dao/model/general/account.gen.go'),
  },
  {
    name: 'Employee',
    filePath: path.resolve(__dirname, '../../backend/dao/model/general/employee.gen.go'),
  },
  {
    name: 'QuoteEmployee',
    filePath: path.resolve(__dirname, '../../backend/dao/model/quote_manage/quote_employee.gen.go'),
  }
]

const OUTPUT_TS_FILE = path.resolve(__dirname, '../src/types/gorm-models.ts')

// Go 类型转 TS 类型的映射
function mapGoTypeToTs(goType) {
  const isPointer = goType.startsWith('*')
  const baseType = isPointer ? goType.substring(1) : goType

  let tsType = 'any'
  if (['int', 'int32', 'int64', 'uint', 'uint32', 'uint64', 'float32', 'float64'].includes(baseType)) {
    tsType = 'number'
  } else if (baseType === 'string') {
    tsType = 'string'
  } else if (baseType === 'bool') {
    tsType = 'boolean'
  } else if (baseType === 'time.Time') {
    tsType = 'string' // 时间类型用 string 表示
  }

  return isPointer ? `${tsType} | null` : tsType
}

function parseGoStruct(filePath, structName) {
  if (!fs.existsSync(filePath)) {
    console.error(`Go 结构体定义文件不存在: ${filePath}`)
    return []
  }

  const content = fs.readFileSync(filePath, 'utf-8')
  const structRegex = new RegExp(`type\\s+${structName}\\s+struct\\s*\\{([\\s\\S]*?)\\}`, 'm')
  const match = content.match(structRegex)

  if (!match) {
    console.warn(`未能在文件 ${filePath} 中找到结构体 ${structName}`)
    return []
  }

  const structBody = match[1]
  const lines = structBody.split('\n')
  const fields = []

  const fieldRegex = /^\s*([A-Za-z0-9_]+)\s+([\*a-zA-Z0-9_\.]+)\s+`[^`]*json:"([^"]+)"[^`]*`/

  for (const line of lines) {
    const m = line.match(fieldRegex)
    if (m) {
      const goFieldName = m[1]
      const goType = m[2]
      const jsonName = m[3].split(',')[0] // 去掉 json 标记中的 omitempty 等
      
      fields.push({
        goFieldName,
        goType,
        jsonName,
        tsType: mapGoTypeToTs(goType)
      })
    }
  }

  return fields
}

function generate() {
  console.log('--- 开始从 GORM 结构体动态生成前端嵌套主从 TypeScript 类型 ---')
  
  const parsedModels = {}
  GO_MODELS.forEach(model => {
    parsedModels[model.name] = parseGoStruct(model.filePath, model.name)
  })

  // 准备输出的内容
  let fileContent = `/**
 * This file is automatically generated by frontend/scripts/generate-types.js at build time.
 * DO NOT EDIT MANUALLY! Any changes will be overwritten during building or running.
 */

`

  // 1. 生成各张表最干净的基础接口（不带有任何残留的非GORM字段）
  Object.keys(parsedModels).forEach(name => {
    fileContent += `export interface Gorm${name} {\n`
    parsedModels[name].forEach(f => {
      fileContent += `  ${f.jsonName}: ${f.tsType}\n`
    })
    fileContent += `}\n\n`
  })

  // 2. 动态生成从表 Account 拥有的默认值对象 (排除密码字段)
  fileContent += `export const DEFAULT_GORM_ACCOUNT: Omit<GormAccount, 'password'> = {\n`
  parsedModels['Account'].forEach(f => {
    if (f.jsonName === 'password') return
    let defVal = 'null'
    if (f.jsonName === 'id') defVal = '0'
    fileContent += `  ${f.jsonName}: ${defVal},\n`
  })
  fileContent += `}\n\n`

  // 3. 动态生成从表 QuoteEmployee 拥有的默认值对象
  fileContent += `export const DEFAULT_GORM_QUOTE_EMPLOYEE: GormQuoteEmployee = {\n`
  parsedModels['QuoteEmployee'].forEach(f => {
    let defVal = 'null'
    if (f.jsonName === 'id') defVal = '0'
    fileContent += `  ${f.jsonName}: ${defVal},\n`
  })
  fileContent += `}\n\n`

  // 4. 生成主从表嵌套关系的核心 User 数据结构（主表是 Employee 表，包含其本身字段，以及嵌套的从表结构体）
  // 去除敏感的 password 字段
  fileContent += `export interface User extends GormEmployee {\n`
  fileContent += `  account: Omit<GormAccount, 'password'> | null\n`
  fileContent += `  quote_employee: GormQuoteEmployee | null\n`
  fileContent += `}\n\n`

  // 5. 生成 User 整体结构的空值默认模板，当没有关联记录时设为 null
  fileContent += `export const DEFAULT_USER_NULL: User = {\n`
  parsedModels['Employee'].forEach(f => {
    let defVal = 'null'
    if (f.jsonName === 'id') defVal = '0'
    fileContent += `  ${f.jsonName}: ${defVal},\n`
  })
  fileContent += `  account: null,\n`
  fileContent += `  quote_employee: null,\n`
  fileContent += `}\n`

  // 确保输出文件夹存在
  const outputDir = path.dirname(OUTPUT_TS_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_TS_FILE, fileContent, 'utf-8')
  console.log(`TS 主从嵌套类型定义生成成功：${OUTPUT_TS_FILE}`)
}

generate()
