// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newAQuoteItem(db *gorm.DB, opts ...gen.DOOption) aQuoteItem {
	_aQuoteItem := aQuoteItem{}

	_aQuoteItem.aQuoteItemDo.UseDB(db, opts...)
	_aQuoteItem.aQuoteItemDo.UseModel(&quote_manage.AQuoteItem{})

	tableName := _aQuoteItem.aQuoteItemDo.TableName()
	_aQuoteItem.ALL = field.NewAsterisk(tableName)
	_aQuoteItem.ID = field.NewInt32(tableName, "id")
	_aQuoteItem.QuoteID = field.NewInt32(tableName, "quote_id")
	_aQuoteItem.ProductCategoryID = field.NewInt32(tableName, "product_category_id")
	_aQuoteItem.ProductCategoryName = field.NewString(tableName, "product_category_name")
	_aQuoteItem.ProductNameID = field.NewInt32(tableName, "product_name_id")
	_aQuoteItem.ProductName = field.NewString(tableName, "product_name")
	_aQuoteItem.SpecificationModel = field.NewString(tableName, "specification_model")
	_aQuoteItem.PriceCatalogVersion = field.NewString(tableName, "price_catalog_version")
	_aQuoteItem.OrderBatchTier = field.NewString(tableName, "order_batch_tier")
	_aQuoteItem.CatalogBasePrice = field.NewFloat64(tableName, "catalog_base_price")
	_aQuoteItem.QuoteFloatRate = field.NewFloat64(tableName, "quote_float_rate")
	_aQuoteItem.QuoteUnitPrice = field.NewFloat64(tableName, "quote_unit_price")
	_aQuoteItem.Quantity = field.NewInt32(tableName, "quantity")
	_aQuoteItem.TotalAmount = field.NewFloat64(tableName, "total_amount")
	_aQuoteItem.IsBelowPriceFloor = field.NewBool(tableName, "is_below_price_floor")
	_aQuoteItem.CreatedAt = field.NewTime(tableName, "created_at")
	_aQuoteItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_aQuoteItem.fillFieldMap()

	return _aQuoteItem
}

type aQuoteItem struct {
	aQuoteItemDo

	ALL                 field.Asterisk
	ID                  field.Int32
	QuoteID             field.Int32
	ProductCategoryID   field.Int32
	ProductCategoryName field.String
	ProductNameID       field.Int32
	ProductName         field.String
	SpecificationModel  field.String
	PriceCatalogVersion field.String
	OrderBatchTier      field.String
	CatalogBasePrice    field.Float64
	QuoteFloatRate      field.Float64
	QuoteUnitPrice      field.Float64
	Quantity            field.Int32
	TotalAmount         field.Float64
	IsBelowPriceFloor   field.Bool
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a aQuoteItem) Table(newTableName string) *aQuoteItem {
	a.aQuoteItemDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aQuoteItem) As(alias string) *aQuoteItem {
	a.aQuoteItemDo.DO = *(a.aQuoteItemDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aQuoteItem) updateTableName(table string) *aQuoteItem {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.QuoteID = field.NewInt32(table, "quote_id")
	a.ProductCategoryID = field.NewInt32(table, "product_category_id")
	a.ProductCategoryName = field.NewString(table, "product_category_name")
	a.ProductNameID = field.NewInt32(table, "product_name_id")
	a.ProductName = field.NewString(table, "product_name")
	a.SpecificationModel = field.NewString(table, "specification_model")
	a.PriceCatalogVersion = field.NewString(table, "price_catalog_version")
	a.OrderBatchTier = field.NewString(table, "order_batch_tier")
	a.CatalogBasePrice = field.NewFloat64(table, "catalog_base_price")
	a.QuoteFloatRate = field.NewFloat64(table, "quote_float_rate")
	a.QuoteUnitPrice = field.NewFloat64(table, "quote_unit_price")
	a.Quantity = field.NewInt32(table, "quantity")
	a.TotalAmount = field.NewFloat64(table, "total_amount")
	a.IsBelowPriceFloor = field.NewBool(table, "is_below_price_floor")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *aQuoteItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aQuoteItem) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 17)
	a.fieldMap["id"] = a.ID
	a.fieldMap["quote_id"] = a.QuoteID
	a.fieldMap["product_category_id"] = a.ProductCategoryID
	a.fieldMap["product_category_name"] = a.ProductCategoryName
	a.fieldMap["product_name_id"] = a.ProductNameID
	a.fieldMap["product_name"] = a.ProductName
	a.fieldMap["specification_model"] = a.SpecificationModel
	a.fieldMap["price_catalog_version"] = a.PriceCatalogVersion
	a.fieldMap["order_batch_tier"] = a.OrderBatchTier
	a.fieldMap["catalog_base_price"] = a.CatalogBasePrice
	a.fieldMap["quote_float_rate"] = a.QuoteFloatRate
	a.fieldMap["quote_unit_price"] = a.QuoteUnitPrice
	a.fieldMap["quantity"] = a.Quantity
	a.fieldMap["total_amount"] = a.TotalAmount
	a.fieldMap["is_below_price_floor"] = a.IsBelowPriceFloor
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a aQuoteItem) clone(db *gorm.DB) aQuoteItem {
	a.aQuoteItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aQuoteItem) replaceDB(db *gorm.DB) aQuoteItem {
	a.aQuoteItemDo.ReplaceDB(db)
	return a
}

type aQuoteItemDo struct{ gen.DO }

type IAQuoteItemDo interface {
	gen.SubQuery
	Debug() IAQuoteItemDo
	WithContext(ctx context.Context) IAQuoteItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAQuoteItemDo
	WriteDB() IAQuoteItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAQuoteItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAQuoteItemDo
	Not(conds ...gen.Condition) IAQuoteItemDo
	Or(conds ...gen.Condition) IAQuoteItemDo
	Select(conds ...field.Expr) IAQuoteItemDo
	Where(conds ...gen.Condition) IAQuoteItemDo
	Order(conds ...field.Expr) IAQuoteItemDo
	Distinct(cols ...field.Expr) IAQuoteItemDo
	Omit(cols ...field.Expr) IAQuoteItemDo
	Join(table schema.Tabler, on ...field.Expr) IAQuoteItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAQuoteItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAQuoteItemDo
	Group(cols ...field.Expr) IAQuoteItemDo
	Having(conds ...gen.Condition) IAQuoteItemDo
	Limit(limit int) IAQuoteItemDo
	Offset(offset int) IAQuoteItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAQuoteItemDo
	Unscoped() IAQuoteItemDo
	Create(values ...*quote_manage.AQuoteItem) error
	CreateInBatches(values []*quote_manage.AQuoteItem, batchSize int) error
	Save(values ...*quote_manage.AQuoteItem) error
	First() (*quote_manage.AQuoteItem, error)
	Take() (*quote_manage.AQuoteItem, error)
	Last() (*quote_manage.AQuoteItem, error)
	Find() ([]*quote_manage.AQuoteItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.AQuoteItem, err error)
	FindInBatches(result *[]*quote_manage.AQuoteItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.AQuoteItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAQuoteItemDo
	Assign(attrs ...field.AssignExpr) IAQuoteItemDo
	Joins(fields ...field.RelationField) IAQuoteItemDo
	Preload(fields ...field.RelationField) IAQuoteItemDo
	FirstOrInit() (*quote_manage.AQuoteItem, error)
	FirstOrCreate() (*quote_manage.AQuoteItem, error)
	FindByPage(offset int, limit int) (result []*quote_manage.AQuoteItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAQuoteItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aQuoteItemDo) Debug() IAQuoteItemDo {
	return a.withDO(a.DO.Debug())
}

func (a aQuoteItemDo) WithContext(ctx context.Context) IAQuoteItemDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aQuoteItemDo) ReadDB() IAQuoteItemDo {
	return a.Clauses(dbresolver.Read)
}

func (a aQuoteItemDo) WriteDB() IAQuoteItemDo {
	return a.Clauses(dbresolver.Write)
}

func (a aQuoteItemDo) Session(config *gorm.Session) IAQuoteItemDo {
	return a.withDO(a.DO.Session(config))
}

func (a aQuoteItemDo) Clauses(conds ...clause.Expression) IAQuoteItemDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aQuoteItemDo) Returning(value interface{}, columns ...string) IAQuoteItemDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aQuoteItemDo) Not(conds ...gen.Condition) IAQuoteItemDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aQuoteItemDo) Or(conds ...gen.Condition) IAQuoteItemDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aQuoteItemDo) Select(conds ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aQuoteItemDo) Where(conds ...gen.Condition) IAQuoteItemDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aQuoteItemDo) Order(conds ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aQuoteItemDo) Distinct(cols ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aQuoteItemDo) Omit(cols ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aQuoteItemDo) Join(table schema.Tabler, on ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aQuoteItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aQuoteItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aQuoteItemDo) Group(cols ...field.Expr) IAQuoteItemDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aQuoteItemDo) Having(conds ...gen.Condition) IAQuoteItemDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aQuoteItemDo) Limit(limit int) IAQuoteItemDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aQuoteItemDo) Offset(offset int) IAQuoteItemDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aQuoteItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAQuoteItemDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aQuoteItemDo) Unscoped() IAQuoteItemDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aQuoteItemDo) Create(values ...*quote_manage.AQuoteItem) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aQuoteItemDo) CreateInBatches(values []*quote_manage.AQuoteItem, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aQuoteItemDo) Save(values ...*quote_manage.AQuoteItem) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aQuoteItemDo) First() (*quote_manage.AQuoteItem, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.AQuoteItem), nil
	}
}

func (a aQuoteItemDo) Take() (*quote_manage.AQuoteItem, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.AQuoteItem), nil
	}
}

func (a aQuoteItemDo) Last() (*quote_manage.AQuoteItem, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.AQuoteItem), nil
	}
}

func (a aQuoteItemDo) Find() ([]*quote_manage.AQuoteItem, error) {
	result, err := a.DO.Find()
	return result.([]*quote_manage.AQuoteItem), err
}

func (a aQuoteItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.AQuoteItem, err error) {
	buf := make([]*quote_manage.AQuoteItem, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aQuoteItemDo) FindInBatches(result *[]*quote_manage.AQuoteItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aQuoteItemDo) Attrs(attrs ...field.AssignExpr) IAQuoteItemDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aQuoteItemDo) Assign(attrs ...field.AssignExpr) IAQuoteItemDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aQuoteItemDo) Joins(fields ...field.RelationField) IAQuoteItemDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aQuoteItemDo) Preload(fields ...field.RelationField) IAQuoteItemDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aQuoteItemDo) FirstOrInit() (*quote_manage.AQuoteItem, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.AQuoteItem), nil
	}
}

func (a aQuoteItemDo) FirstOrCreate() (*quote_manage.AQuoteItem, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.AQuoteItem), nil
	}
}

func (a aQuoteItemDo) FindByPage(offset int, limit int) (result []*quote_manage.AQuoteItem, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aQuoteItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aQuoteItemDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aQuoteItemDo) Delete(models ...*quote_manage.AQuoteItem) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aQuoteItemDo) withDO(do gen.Dao) *aQuoteItemDo {
	a.DO = *do.(*gen.DO)
	return a
}
