// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		AQuoteItem:       newAQuoteItem(db, opts...),
		BQuoteItem:       newBQuoteItem(db, opts...),
		CostWorksheet:    newCostWorksheet(db, opts...),
		EmployeeRole:     newEmployeeRole(db, opts...),
		MainCategory:     newMainCategory(db, opts...),
		ProductSpec:      newProductSpec(db, opts...),
		Quote:            newQuote(db, opts...),
		QuoteProcess:     newQuoteProcess(db, opts...),
		QuoteProcessNode: newQuoteProcessNode(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AQuoteItem       aQuoteItem
	BQuoteItem       bQuoteItem
	CostWorksheet    costWorksheet
	EmployeeRole     employeeRole
	MainCategory     mainCategory
	ProductSpec      productSpec
	Quote            quote
	QuoteProcess     quoteProcess
	QuoteProcessNode quoteProcessNode
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AQuoteItem:       q.AQuoteItem.clone(db),
		BQuoteItem:       q.BQuoteItem.clone(db),
		CostWorksheet:    q.CostWorksheet.clone(db),
		EmployeeRole:     q.EmployeeRole.clone(db),
		MainCategory:     q.MainCategory.clone(db),
		ProductSpec:      q.ProductSpec.clone(db),
		Quote:            q.Quote.clone(db),
		QuoteProcess:     q.QuoteProcess.clone(db),
		QuoteProcessNode: q.QuoteProcessNode.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AQuoteItem:       q.AQuoteItem.replaceDB(db),
		BQuoteItem:       q.BQuoteItem.replaceDB(db),
		CostWorksheet:    q.CostWorksheet.replaceDB(db),
		EmployeeRole:     q.EmployeeRole.replaceDB(db),
		MainCategory:     q.MainCategory.replaceDB(db),
		ProductSpec:      q.ProductSpec.replaceDB(db),
		Quote:            q.Quote.replaceDB(db),
		QuoteProcess:     q.QuoteProcess.replaceDB(db),
		QuoteProcessNode: q.QuoteProcessNode.replaceDB(db),
	}
}

type queryCtx struct {
	AQuoteItem       IAQuoteItemDo
	BQuoteItem       IBQuoteItemDo
	CostWorksheet    ICostWorksheetDo
	EmployeeRole     IEmployeeRoleDo
	MainCategory     IMainCategoryDo
	ProductSpec      IProductSpecDo
	Quote            IQuoteDo
	QuoteProcess     IQuoteProcessDo
	QuoteProcessNode IQuoteProcessNodeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AQuoteItem:       q.AQuoteItem.WithContext(ctx),
		BQuoteItem:       q.BQuoteItem.WithContext(ctx),
		CostWorksheet:    q.CostWorksheet.WithContext(ctx),
		EmployeeRole:     q.EmployeeRole.WithContext(ctx),
		MainCategory:     q.MainCategory.WithContext(ctx),
		ProductSpec:      q.ProductSpec.WithContext(ctx),
		Quote:            q.Quote.WithContext(ctx),
		QuoteProcess:     q.QuoteProcess.WithContext(ctx),
		QuoteProcessNode: q.QuoteProcessNode.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
