// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newQuoteProcess(db *gorm.DB, opts ...gen.DOOption) quoteProcess {
	_quoteProcess := quoteProcess{}

	_quoteProcess.quoteProcessDo.UseDB(db, opts...)
	_quoteProcess.quoteProcessDo.UseModel(&quote_manage.QuoteProcess{})

	tableName := _quoteProcess.quoteProcessDo.TableName()
	_quoteProcess.ALL = field.NewAsterisk(tableName)
	_quoteProcess.ID = field.NewInt32(tableName, "id")
	_quoteProcess.QuoteID = field.NewInt32(tableName, "quote_id")
	_quoteProcess.CreateEmployeeID = field.NewInt32(tableName, "create_employee_id")
	_quoteProcess.CreateEmployeeName = field.NewString(tableName, "create_employee_name")
	_quoteProcess.PresentNodeID = field.NewInt32(tableName, "present_node_id")
	_quoteProcess.PresentNodeName = field.NewString(tableName, "present_node_name")
	_quoteProcess.PresentStatus = field.NewString(tableName, "present_status")
	_quoteProcess.PresentApproverID = field.NewInt32(tableName, "present_approver_id")
	_quoteProcess.PresentApproverName = field.NewString(tableName, "present_approver_name")
	_quoteProcess.CreatedAt = field.NewString(tableName, "created_at")

	_quoteProcess.fillFieldMap()

	return _quoteProcess
}

type quoteProcess struct {
	quoteProcessDo

	ALL                 field.Asterisk
	ID                  field.Int32
	QuoteID             field.Int32
	CreateEmployeeID    field.Int32
	CreateEmployeeName  field.String
	PresentNodeID       field.Int32
	PresentNodeName     field.String
	PresentStatus       field.String
	PresentApproverID   field.Int32
	PresentApproverName field.String
	CreatedAt           field.String

	fieldMap map[string]field.Expr
}

func (q quoteProcess) Table(newTableName string) *quoteProcess {
	q.quoteProcessDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quoteProcess) As(alias string) *quoteProcess {
	q.quoteProcessDo.DO = *(q.quoteProcessDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quoteProcess) updateTableName(table string) *quoteProcess {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.QuoteID = field.NewInt32(table, "quote_id")
	q.CreateEmployeeID = field.NewInt32(table, "create_employee_id")
	q.CreateEmployeeName = field.NewString(table, "create_employee_name")
	q.PresentNodeID = field.NewInt32(table, "present_node_id")
	q.PresentNodeName = field.NewString(table, "present_node_name")
	q.PresentStatus = field.NewString(table, "present_status")
	q.PresentApproverID = field.NewInt32(table, "present_approver_id")
	q.PresentApproverName = field.NewString(table, "present_approver_name")
	q.CreatedAt = field.NewString(table, "created_at")

	q.fillFieldMap()

	return q
}

func (q *quoteProcess) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quoteProcess) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 10)
	q.fieldMap["id"] = q.ID
	q.fieldMap["quote_id"] = q.QuoteID
	q.fieldMap["create_employee_id"] = q.CreateEmployeeID
	q.fieldMap["create_employee_name"] = q.CreateEmployeeName
	q.fieldMap["present_node_id"] = q.PresentNodeID
	q.fieldMap["present_node_name"] = q.PresentNodeName
	q.fieldMap["present_status"] = q.PresentStatus
	q.fieldMap["present_approver_id"] = q.PresentApproverID
	q.fieldMap["present_approver_name"] = q.PresentApproverName
	q.fieldMap["created_at"] = q.CreatedAt
}

func (q quoteProcess) clone(db *gorm.DB) quoteProcess {
	q.quoteProcessDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quoteProcess) replaceDB(db *gorm.DB) quoteProcess {
	q.quoteProcessDo.ReplaceDB(db)
	return q
}

type quoteProcessDo struct{ gen.DO }

type IQuoteProcessDo interface {
	gen.SubQuery
	Debug() IQuoteProcessDo
	WithContext(ctx context.Context) IQuoteProcessDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuoteProcessDo
	WriteDB() IQuoteProcessDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuoteProcessDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuoteProcessDo
	Not(conds ...gen.Condition) IQuoteProcessDo
	Or(conds ...gen.Condition) IQuoteProcessDo
	Select(conds ...field.Expr) IQuoteProcessDo
	Where(conds ...gen.Condition) IQuoteProcessDo
	Order(conds ...field.Expr) IQuoteProcessDo
	Distinct(cols ...field.Expr) IQuoteProcessDo
	Omit(cols ...field.Expr) IQuoteProcessDo
	Join(table schema.Tabler, on ...field.Expr) IQuoteProcessDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessDo
	Group(cols ...field.Expr) IQuoteProcessDo
	Having(conds ...gen.Condition) IQuoteProcessDo
	Limit(limit int) IQuoteProcessDo
	Offset(offset int) IQuoteProcessDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteProcessDo
	Unscoped() IQuoteProcessDo
	Create(values ...*quote_manage.QuoteProcess) error
	CreateInBatches(values []*quote_manage.QuoteProcess, batchSize int) error
	Save(values ...*quote_manage.QuoteProcess) error
	First() (*quote_manage.QuoteProcess, error)
	Take() (*quote_manage.QuoteProcess, error)
	Last() (*quote_manage.QuoteProcess, error)
	Find() ([]*quote_manage.QuoteProcess, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.QuoteProcess, err error)
	FindInBatches(result *[]*quote_manage.QuoteProcess, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.QuoteProcess) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuoteProcessDo
	Assign(attrs ...field.AssignExpr) IQuoteProcessDo
	Joins(fields ...field.RelationField) IQuoteProcessDo
	Preload(fields ...field.RelationField) IQuoteProcessDo
	FirstOrInit() (*quote_manage.QuoteProcess, error)
	FirstOrCreate() (*quote_manage.QuoteProcess, error)
	FindByPage(offset int, limit int) (result []*quote_manage.QuoteProcess, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuoteProcessDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quoteProcessDo) Debug() IQuoteProcessDo {
	return q.withDO(q.DO.Debug())
}

func (q quoteProcessDo) WithContext(ctx context.Context) IQuoteProcessDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quoteProcessDo) ReadDB() IQuoteProcessDo {
	return q.Clauses(dbresolver.Read)
}

func (q quoteProcessDo) WriteDB() IQuoteProcessDo {
	return q.Clauses(dbresolver.Write)
}

func (q quoteProcessDo) Session(config *gorm.Session) IQuoteProcessDo {
	return q.withDO(q.DO.Session(config))
}

func (q quoteProcessDo) Clauses(conds ...clause.Expression) IQuoteProcessDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quoteProcessDo) Returning(value interface{}, columns ...string) IQuoteProcessDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quoteProcessDo) Not(conds ...gen.Condition) IQuoteProcessDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quoteProcessDo) Or(conds ...gen.Condition) IQuoteProcessDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quoteProcessDo) Select(conds ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quoteProcessDo) Where(conds ...gen.Condition) IQuoteProcessDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quoteProcessDo) Order(conds ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quoteProcessDo) Distinct(cols ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quoteProcessDo) Omit(cols ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quoteProcessDo) Join(table schema.Tabler, on ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quoteProcessDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quoteProcessDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quoteProcessDo) Group(cols ...field.Expr) IQuoteProcessDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quoteProcessDo) Having(conds ...gen.Condition) IQuoteProcessDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quoteProcessDo) Limit(limit int) IQuoteProcessDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quoteProcessDo) Offset(offset int) IQuoteProcessDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quoteProcessDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteProcessDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quoteProcessDo) Unscoped() IQuoteProcessDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quoteProcessDo) Create(values ...*quote_manage.QuoteProcess) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quoteProcessDo) CreateInBatches(values []*quote_manage.QuoteProcess, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quoteProcessDo) Save(values ...*quote_manage.QuoteProcess) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quoteProcessDo) First() (*quote_manage.QuoteProcess, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcess), nil
	}
}

func (q quoteProcessDo) Take() (*quote_manage.QuoteProcess, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcess), nil
	}
}

func (q quoteProcessDo) Last() (*quote_manage.QuoteProcess, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcess), nil
	}
}

func (q quoteProcessDo) Find() ([]*quote_manage.QuoteProcess, error) {
	result, err := q.DO.Find()
	return result.([]*quote_manage.QuoteProcess), err
}

func (q quoteProcessDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.QuoteProcess, err error) {
	buf := make([]*quote_manage.QuoteProcess, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quoteProcessDo) FindInBatches(result *[]*quote_manage.QuoteProcess, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quoteProcessDo) Attrs(attrs ...field.AssignExpr) IQuoteProcessDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quoteProcessDo) Assign(attrs ...field.AssignExpr) IQuoteProcessDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quoteProcessDo) Joins(fields ...field.RelationField) IQuoteProcessDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quoteProcessDo) Preload(fields ...field.RelationField) IQuoteProcessDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quoteProcessDo) FirstOrInit() (*quote_manage.QuoteProcess, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcess), nil
	}
}

func (q quoteProcessDo) FirstOrCreate() (*quote_manage.QuoteProcess, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcess), nil
	}
}

func (q quoteProcessDo) FindByPage(offset int, limit int) (result []*quote_manage.QuoteProcess, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quoteProcessDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quoteProcessDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quoteProcessDo) Delete(models ...*quote_manage.QuoteProcess) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quoteProcessDo) withDO(do gen.Dao) *quoteProcessDo {
	q.DO = *do.(*gen.DO)
	return q
}
