// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newMainCategory(db *gorm.DB, opts ...gen.DOOption) mainCategory {
	_mainCategory := mainCategory{}

	_mainCategory.mainCategoryDo.UseDB(db, opts...)
	_mainCategory.mainCategoryDo.UseModel(&quote_manage.MainCategory{})

	tableName := _mainCategory.mainCategoryDo.TableName()
	_mainCategory.ALL = field.NewAsterisk(tableName)
	_mainCategory.ID = field.NewInt32(tableName, "id")
	_mainCategory.MainCategoryName = field.NewString(tableName, "main_category_name")

	_mainCategory.fillFieldMap()

	return _mainCategory
}

type mainCategory struct {
	mainCategoryDo

	ALL              field.Asterisk
	ID               field.Int32
	MainCategoryName field.String

	fieldMap map[string]field.Expr
}

func (m mainCategory) Table(newTableName string) *mainCategory {
	m.mainCategoryDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mainCategory) As(alias string) *mainCategory {
	m.mainCategoryDo.DO = *(m.mainCategoryDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mainCategory) updateTableName(table string) *mainCategory {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.MainCategoryName = field.NewString(table, "main_category_name")

	m.fillFieldMap()

	return m
}

func (m *mainCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mainCategory) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 2)
	m.fieldMap["id"] = m.ID
	m.fieldMap["main_category_name"] = m.MainCategoryName
}

func (m mainCategory) clone(db *gorm.DB) mainCategory {
	m.mainCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mainCategory) replaceDB(db *gorm.DB) mainCategory {
	m.mainCategoryDo.ReplaceDB(db)
	return m
}

type mainCategoryDo struct{ gen.DO }

type IMainCategoryDo interface {
	gen.SubQuery
	Debug() IMainCategoryDo
	WithContext(ctx context.Context) IMainCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMainCategoryDo
	WriteDB() IMainCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMainCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMainCategoryDo
	Not(conds ...gen.Condition) IMainCategoryDo
	Or(conds ...gen.Condition) IMainCategoryDo
	Select(conds ...field.Expr) IMainCategoryDo
	Where(conds ...gen.Condition) IMainCategoryDo
	Order(conds ...field.Expr) IMainCategoryDo
	Distinct(cols ...field.Expr) IMainCategoryDo
	Omit(cols ...field.Expr) IMainCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IMainCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMainCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMainCategoryDo
	Group(cols ...field.Expr) IMainCategoryDo
	Having(conds ...gen.Condition) IMainCategoryDo
	Limit(limit int) IMainCategoryDo
	Offset(offset int) IMainCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMainCategoryDo
	Unscoped() IMainCategoryDo
	Create(values ...*quote_manage.MainCategory) error
	CreateInBatches(values []*quote_manage.MainCategory, batchSize int) error
	Save(values ...*quote_manage.MainCategory) error
	First() (*quote_manage.MainCategory, error)
	Take() (*quote_manage.MainCategory, error)
	Last() (*quote_manage.MainCategory, error)
	Find() ([]*quote_manage.MainCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.MainCategory, err error)
	FindInBatches(result *[]*quote_manage.MainCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.MainCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMainCategoryDo
	Assign(attrs ...field.AssignExpr) IMainCategoryDo
	Joins(fields ...field.RelationField) IMainCategoryDo
	Preload(fields ...field.RelationField) IMainCategoryDo
	FirstOrInit() (*quote_manage.MainCategory, error)
	FirstOrCreate() (*quote_manage.MainCategory, error)
	FindByPage(offset int, limit int) (result []*quote_manage.MainCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMainCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mainCategoryDo) Debug() IMainCategoryDo {
	return m.withDO(m.DO.Debug())
}

func (m mainCategoryDo) WithContext(ctx context.Context) IMainCategoryDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mainCategoryDo) ReadDB() IMainCategoryDo {
	return m.Clauses(dbresolver.Read)
}

func (m mainCategoryDo) WriteDB() IMainCategoryDo {
	return m.Clauses(dbresolver.Write)
}

func (m mainCategoryDo) Session(config *gorm.Session) IMainCategoryDo {
	return m.withDO(m.DO.Session(config))
}

func (m mainCategoryDo) Clauses(conds ...clause.Expression) IMainCategoryDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mainCategoryDo) Returning(value interface{}, columns ...string) IMainCategoryDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mainCategoryDo) Not(conds ...gen.Condition) IMainCategoryDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mainCategoryDo) Or(conds ...gen.Condition) IMainCategoryDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mainCategoryDo) Select(conds ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mainCategoryDo) Where(conds ...gen.Condition) IMainCategoryDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mainCategoryDo) Order(conds ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mainCategoryDo) Distinct(cols ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mainCategoryDo) Omit(cols ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mainCategoryDo) Join(table schema.Tabler, on ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mainCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mainCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mainCategoryDo) Group(cols ...field.Expr) IMainCategoryDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mainCategoryDo) Having(conds ...gen.Condition) IMainCategoryDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mainCategoryDo) Limit(limit int) IMainCategoryDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mainCategoryDo) Offset(offset int) IMainCategoryDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mainCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMainCategoryDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mainCategoryDo) Unscoped() IMainCategoryDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mainCategoryDo) Create(values ...*quote_manage.MainCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mainCategoryDo) CreateInBatches(values []*quote_manage.MainCategory, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mainCategoryDo) Save(values ...*quote_manage.MainCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mainCategoryDo) First() (*quote_manage.MainCategory, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.MainCategory), nil
	}
}

func (m mainCategoryDo) Take() (*quote_manage.MainCategory, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.MainCategory), nil
	}
}

func (m mainCategoryDo) Last() (*quote_manage.MainCategory, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.MainCategory), nil
	}
}

func (m mainCategoryDo) Find() ([]*quote_manage.MainCategory, error) {
	result, err := m.DO.Find()
	return result.([]*quote_manage.MainCategory), err
}

func (m mainCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.MainCategory, err error) {
	buf := make([]*quote_manage.MainCategory, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mainCategoryDo) FindInBatches(result *[]*quote_manage.MainCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mainCategoryDo) Attrs(attrs ...field.AssignExpr) IMainCategoryDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mainCategoryDo) Assign(attrs ...field.AssignExpr) IMainCategoryDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mainCategoryDo) Joins(fields ...field.RelationField) IMainCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mainCategoryDo) Preload(fields ...field.RelationField) IMainCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mainCategoryDo) FirstOrInit() (*quote_manage.MainCategory, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.MainCategory), nil
	}
}

func (m mainCategoryDo) FirstOrCreate() (*quote_manage.MainCategory, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.MainCategory), nil
	}
}

func (m mainCategoryDo) FindByPage(offset int, limit int) (result []*quote_manage.MainCategory, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mainCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mainCategoryDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mainCategoryDo) Delete(models ...*quote_manage.MainCategory) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mainCategoryDo) withDO(do gen.Dao) *mainCategoryDo {
	m.DO = *do.(*gen.DO)
	return m
}
