// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newBQuoteItem(db *gorm.DB, opts ...gen.DOOption) bQuoteItem {
	_bQuoteItem := bQuoteItem{}

	_bQuoteItem.bQuoteItemDo.UseDB(db, opts...)
	_bQuoteItem.bQuoteItemDo.UseModel(&quote_manage.BQuoteItem{})

	tableName := _bQuoteItem.bQuoteItemDo.TableName()
	_bQuoteItem.ALL = field.NewAsterisk(tableName)
	_bQuoteItem.ID = field.NewInt32(tableName, "id")
	_bQuoteItem.QuoteID = field.NewInt32(tableName, "quote_id")
	_bQuoteItem.ProductNameID = field.NewInt32(tableName, "product_name_id")
	_bQuoteItem.ProductName = field.NewString(tableName, "product_name")
	_bQuoteItem.SpecificationModelID = field.NewInt32(tableName, "specification_model_id")
	_bQuoteItem.SpecificationModel = field.NewString(tableName, "specification_model")
	_bQuoteItem.BasePrice = field.NewFloat64(tableName, "base_price")
	_bQuoteItem.BatchTier = field.NewString(tableName, "batch_tier")
	_bQuoteItem.DimensionParams = field.NewString(tableName, "dimension_params")
	_bQuoteItem.DimensionFactor = field.NewString(tableName, "dimension_factor")
	_bQuoteItem.ProcessParams = field.NewString(tableName, "process_params")
	_bQuoteItem.ProcessFactor = field.NewString(tableName, "process_factor")
	_bQuoteItem.PurityFactor = field.NewString(tableName, "purity_factor")
	_bQuoteItem.MaterialTotalFactor = field.NewString(tableName, "material_total_factor")
	_bQuoteItem.LaborTotalFactor = field.NewString(tableName, "labor_total_factor")
	_bQuoteItem.ManuCostTotalFactor = field.NewString(tableName, "manu_cost_total_factor")
	_bQuoteItem.Material = field.NewString(tableName, "material")
	_bQuoteItem.BaseMaterialCost = field.NewFloat64(tableName, "base_material_cost")
	_bQuoteItem.BaseLaborCost = field.NewFloat64(tableName, "base_labor_cost")
	_bQuoteItem.BaseVariOverhead = field.NewFloat64(tableName, "base_vari_overhead")
	_bQuoteItem.BaseFixedOverhead = field.NewFloat64(tableName, "base_fixed_overhead")
	_bQuoteItem.BasePeriodExpense = field.NewFloat64(tableName, "base_period_expense")
	_bQuoteItem.BatchFactor = field.NewString(tableName, "batch_factor")
	_bQuoteItem.FinalBasePrice = field.NewFloat64(tableName, "final_base_price")
	_bQuoteItem.QuoteUnitPrice = field.NewFloat64(tableName, "quote_unit_price")
	_bQuoteItem.Quantity = field.NewString(tableName, "quantity")

	_bQuoteItem.fillFieldMap()

	return _bQuoteItem
}

type bQuoteItem struct {
	bQuoteItemDo

	ALL                  field.Asterisk
	ID                   field.Int32
	QuoteID              field.Int32
	ProductNameID        field.Int32
	ProductName          field.String
	SpecificationModelID field.Int32
	SpecificationModel   field.String
	BasePrice            field.Float64
	BatchTier            field.String
	DimensionParams      field.String
	DimensionFactor      field.String
	ProcessParams        field.String
	ProcessFactor        field.String
	PurityFactor         field.String
	MaterialTotalFactor  field.String
	LaborTotalFactor     field.String
	ManuCostTotalFactor  field.String
	Material             field.String
	BaseMaterialCost     field.Float64
	BaseLaborCost        field.Float64
	BaseVariOverhead     field.Float64
	BaseFixedOverhead    field.Float64
	BasePeriodExpense    field.Float64
	BatchFactor          field.String
	FinalBasePrice       field.Float64
	QuoteUnitPrice       field.Float64
	Quantity             field.String

	fieldMap map[string]field.Expr
}

func (b bQuoteItem) Table(newTableName string) *bQuoteItem {
	b.bQuoteItemDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bQuoteItem) As(alias string) *bQuoteItem {
	b.bQuoteItemDo.DO = *(b.bQuoteItemDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bQuoteItem) updateTableName(table string) *bQuoteItem {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt32(table, "id")
	b.QuoteID = field.NewInt32(table, "quote_id")
	b.ProductNameID = field.NewInt32(table, "product_name_id")
	b.ProductName = field.NewString(table, "product_name")
	b.SpecificationModelID = field.NewInt32(table, "specification_model_id")
	b.SpecificationModel = field.NewString(table, "specification_model")
	b.BasePrice = field.NewFloat64(table, "base_price")
	b.BatchTier = field.NewString(table, "batch_tier")
	b.DimensionParams = field.NewString(table, "dimension_params")
	b.DimensionFactor = field.NewString(table, "dimension_factor")
	b.ProcessParams = field.NewString(table, "process_params")
	b.ProcessFactor = field.NewString(table, "process_factor")
	b.PurityFactor = field.NewString(table, "purity_factor")
	b.MaterialTotalFactor = field.NewString(table, "material_total_factor")
	b.LaborTotalFactor = field.NewString(table, "labor_total_factor")
	b.ManuCostTotalFactor = field.NewString(table, "manu_cost_total_factor")
	b.Material = field.NewString(table, "material")
	b.BaseMaterialCost = field.NewFloat64(table, "base_material_cost")
	b.BaseLaborCost = field.NewFloat64(table, "base_labor_cost")
	b.BaseVariOverhead = field.NewFloat64(table, "base_vari_overhead")
	b.BaseFixedOverhead = field.NewFloat64(table, "base_fixed_overhead")
	b.BasePeriodExpense = field.NewFloat64(table, "base_period_expense")
	b.BatchFactor = field.NewString(table, "batch_factor")
	b.FinalBasePrice = field.NewFloat64(table, "final_base_price")
	b.QuoteUnitPrice = field.NewFloat64(table, "quote_unit_price")
	b.Quantity = field.NewString(table, "quantity")

	b.fillFieldMap()

	return b
}

func (b *bQuoteItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bQuoteItem) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 26)
	b.fieldMap["id"] = b.ID
	b.fieldMap["quote_id"] = b.QuoteID
	b.fieldMap["product_name_id"] = b.ProductNameID
	b.fieldMap["product_name"] = b.ProductName
	b.fieldMap["specification_model_id"] = b.SpecificationModelID
	b.fieldMap["specification_model"] = b.SpecificationModel
	b.fieldMap["base_price"] = b.BasePrice
	b.fieldMap["batch_tier"] = b.BatchTier
	b.fieldMap["dimension_params"] = b.DimensionParams
	b.fieldMap["dimension_factor"] = b.DimensionFactor
	b.fieldMap["process_params"] = b.ProcessParams
	b.fieldMap["process_factor"] = b.ProcessFactor
	b.fieldMap["purity_factor"] = b.PurityFactor
	b.fieldMap["material_total_factor"] = b.MaterialTotalFactor
	b.fieldMap["labor_total_factor"] = b.LaborTotalFactor
	b.fieldMap["manu_cost_total_factor"] = b.ManuCostTotalFactor
	b.fieldMap["material"] = b.Material
	b.fieldMap["base_material_cost"] = b.BaseMaterialCost
	b.fieldMap["base_labor_cost"] = b.BaseLaborCost
	b.fieldMap["base_vari_overhead"] = b.BaseVariOverhead
	b.fieldMap["base_fixed_overhead"] = b.BaseFixedOverhead
	b.fieldMap["base_period_expense"] = b.BasePeriodExpense
	b.fieldMap["batch_factor"] = b.BatchFactor
	b.fieldMap["final_base_price"] = b.FinalBasePrice
	b.fieldMap["quote_unit_price"] = b.QuoteUnitPrice
	b.fieldMap["quantity"] = b.Quantity
}

func (b bQuoteItem) clone(db *gorm.DB) bQuoteItem {
	b.bQuoteItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bQuoteItem) replaceDB(db *gorm.DB) bQuoteItem {
	b.bQuoteItemDo.ReplaceDB(db)
	return b
}

type bQuoteItemDo struct{ gen.DO }

type IBQuoteItemDo interface {
	gen.SubQuery
	Debug() IBQuoteItemDo
	WithContext(ctx context.Context) IBQuoteItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBQuoteItemDo
	WriteDB() IBQuoteItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBQuoteItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBQuoteItemDo
	Not(conds ...gen.Condition) IBQuoteItemDo
	Or(conds ...gen.Condition) IBQuoteItemDo
	Select(conds ...field.Expr) IBQuoteItemDo
	Where(conds ...gen.Condition) IBQuoteItemDo
	Order(conds ...field.Expr) IBQuoteItemDo
	Distinct(cols ...field.Expr) IBQuoteItemDo
	Omit(cols ...field.Expr) IBQuoteItemDo
	Join(table schema.Tabler, on ...field.Expr) IBQuoteItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBQuoteItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBQuoteItemDo
	Group(cols ...field.Expr) IBQuoteItemDo
	Having(conds ...gen.Condition) IBQuoteItemDo
	Limit(limit int) IBQuoteItemDo
	Offset(offset int) IBQuoteItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBQuoteItemDo
	Unscoped() IBQuoteItemDo
	Create(values ...*quote_manage.BQuoteItem) error
	CreateInBatches(values []*quote_manage.BQuoteItem, batchSize int) error
	Save(values ...*quote_manage.BQuoteItem) error
	First() (*quote_manage.BQuoteItem, error)
	Take() (*quote_manage.BQuoteItem, error)
	Last() (*quote_manage.BQuoteItem, error)
	Find() ([]*quote_manage.BQuoteItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.BQuoteItem, err error)
	FindInBatches(result *[]*quote_manage.BQuoteItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.BQuoteItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBQuoteItemDo
	Assign(attrs ...field.AssignExpr) IBQuoteItemDo
	Joins(fields ...field.RelationField) IBQuoteItemDo
	Preload(fields ...field.RelationField) IBQuoteItemDo
	FirstOrInit() (*quote_manage.BQuoteItem, error)
	FirstOrCreate() (*quote_manage.BQuoteItem, error)
	FindByPage(offset int, limit int) (result []*quote_manage.BQuoteItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBQuoteItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bQuoteItemDo) Debug() IBQuoteItemDo {
	return b.withDO(b.DO.Debug())
}

func (b bQuoteItemDo) WithContext(ctx context.Context) IBQuoteItemDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bQuoteItemDo) ReadDB() IBQuoteItemDo {
	return b.Clauses(dbresolver.Read)
}

func (b bQuoteItemDo) WriteDB() IBQuoteItemDo {
	return b.Clauses(dbresolver.Write)
}

func (b bQuoteItemDo) Session(config *gorm.Session) IBQuoteItemDo {
	return b.withDO(b.DO.Session(config))
}

func (b bQuoteItemDo) Clauses(conds ...clause.Expression) IBQuoteItemDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bQuoteItemDo) Returning(value interface{}, columns ...string) IBQuoteItemDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bQuoteItemDo) Not(conds ...gen.Condition) IBQuoteItemDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bQuoteItemDo) Or(conds ...gen.Condition) IBQuoteItemDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bQuoteItemDo) Select(conds ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bQuoteItemDo) Where(conds ...gen.Condition) IBQuoteItemDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bQuoteItemDo) Order(conds ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bQuoteItemDo) Distinct(cols ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bQuoteItemDo) Omit(cols ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bQuoteItemDo) Join(table schema.Tabler, on ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bQuoteItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bQuoteItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bQuoteItemDo) Group(cols ...field.Expr) IBQuoteItemDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bQuoteItemDo) Having(conds ...gen.Condition) IBQuoteItemDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bQuoteItemDo) Limit(limit int) IBQuoteItemDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bQuoteItemDo) Offset(offset int) IBQuoteItemDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bQuoteItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBQuoteItemDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bQuoteItemDo) Unscoped() IBQuoteItemDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bQuoteItemDo) Create(values ...*quote_manage.BQuoteItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bQuoteItemDo) CreateInBatches(values []*quote_manage.BQuoteItem, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bQuoteItemDo) Save(values ...*quote_manage.BQuoteItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bQuoteItemDo) First() (*quote_manage.BQuoteItem, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.BQuoteItem), nil
	}
}

func (b bQuoteItemDo) Take() (*quote_manage.BQuoteItem, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.BQuoteItem), nil
	}
}

func (b bQuoteItemDo) Last() (*quote_manage.BQuoteItem, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.BQuoteItem), nil
	}
}

func (b bQuoteItemDo) Find() ([]*quote_manage.BQuoteItem, error) {
	result, err := b.DO.Find()
	return result.([]*quote_manage.BQuoteItem), err
}

func (b bQuoteItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.BQuoteItem, err error) {
	buf := make([]*quote_manage.BQuoteItem, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bQuoteItemDo) FindInBatches(result *[]*quote_manage.BQuoteItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bQuoteItemDo) Attrs(attrs ...field.AssignExpr) IBQuoteItemDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bQuoteItemDo) Assign(attrs ...field.AssignExpr) IBQuoteItemDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bQuoteItemDo) Joins(fields ...field.RelationField) IBQuoteItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bQuoteItemDo) Preload(fields ...field.RelationField) IBQuoteItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bQuoteItemDo) FirstOrInit() (*quote_manage.BQuoteItem, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.BQuoteItem), nil
	}
}

func (b bQuoteItemDo) FirstOrCreate() (*quote_manage.BQuoteItem, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.BQuoteItem), nil
	}
}

func (b bQuoteItemDo) FindByPage(offset int, limit int) (result []*quote_manage.BQuoteItem, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bQuoteItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bQuoteItemDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bQuoteItemDo) Delete(models ...*quote_manage.BQuoteItem) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bQuoteItemDo) withDO(do gen.Dao) *bQuoteItemDo {
	b.DO = *do.(*gen.DO)
	return b
}
