// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newProductSpec(db *gorm.DB, opts ...gen.DOOption) productSpec {
	_productSpec := productSpec{}

	_productSpec.productSpecDo.UseDB(db, opts...)
	_productSpec.productSpecDo.UseModel(&quote_manage.ProductSpec{})

	tableName := _productSpec.productSpecDo.TableName()
	_productSpec.ALL = field.NewAsterisk(tableName)
	_productSpec.ID = field.NewInt32(tableName, "id")
	_productSpec.MainCategory = field.NewString(tableName, "main_category")
	_productSpec.ProductName = field.NewString(tableName, "product_name")
	_productSpec.Spec = field.NewString(tableName, "spec")
	_productSpec.HighThreshold = field.NewInt32(tableName, "high_threshold")
	_productSpec.LowThreshold = field.NewInt32(tableName, "low_threshold")
	_productSpec.BigBatchPrice = field.NewFloat64(tableName, "big_batch_price")
	_productSpec.MiddleBatchPrice = field.NewFloat64(tableName, "middle_batch_price")
	_productSpec.SmallBatchPrice = field.NewFloat64(tableName, "small_batch_price")

	_productSpec.fillFieldMap()

	return _productSpec
}

type productSpec struct {
	productSpecDo

	ALL              field.Asterisk
	ID               field.Int32
	MainCategory     field.String
	ProductName      field.String
	Spec             field.String
	HighThreshold    field.Int32
	LowThreshold     field.Int32
	BigBatchPrice    field.Float64
	MiddleBatchPrice field.Float64
	SmallBatchPrice  field.Float64

	fieldMap map[string]field.Expr
}

func (p productSpec) Table(newTableName string) *productSpec {
	p.productSpecDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productSpec) As(alias string) *productSpec {
	p.productSpecDo.DO = *(p.productSpecDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productSpec) updateTableName(table string) *productSpec {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.MainCategory = field.NewString(table, "main_category")
	p.ProductName = field.NewString(table, "product_name")
	p.Spec = field.NewString(table, "spec")
	p.HighThreshold = field.NewInt32(table, "high_threshold")
	p.LowThreshold = field.NewInt32(table, "low_threshold")
	p.BigBatchPrice = field.NewFloat64(table, "big_batch_price")
	p.MiddleBatchPrice = field.NewFloat64(table, "middle_batch_price")
	p.SmallBatchPrice = field.NewFloat64(table, "small_batch_price")

	p.fillFieldMap()

	return p
}

func (p *productSpec) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productSpec) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["main_category"] = p.MainCategory
	p.fieldMap["product_name"] = p.ProductName
	p.fieldMap["spec"] = p.Spec
	p.fieldMap["high_threshold"] = p.HighThreshold
	p.fieldMap["low_threshold"] = p.LowThreshold
	p.fieldMap["big_batch_price"] = p.BigBatchPrice
	p.fieldMap["middle_batch_price"] = p.MiddleBatchPrice
	p.fieldMap["small_batch_price"] = p.SmallBatchPrice
}

func (p productSpec) clone(db *gorm.DB) productSpec {
	p.productSpecDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productSpec) replaceDB(db *gorm.DB) productSpec {
	p.productSpecDo.ReplaceDB(db)
	return p
}

type productSpecDo struct{ gen.DO }

type IProductSpecDo interface {
	gen.SubQuery
	Debug() IProductSpecDo
	WithContext(ctx context.Context) IProductSpecDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductSpecDo
	WriteDB() IProductSpecDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductSpecDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductSpecDo
	Not(conds ...gen.Condition) IProductSpecDo
	Or(conds ...gen.Condition) IProductSpecDo
	Select(conds ...field.Expr) IProductSpecDo
	Where(conds ...gen.Condition) IProductSpecDo
	Order(conds ...field.Expr) IProductSpecDo
	Distinct(cols ...field.Expr) IProductSpecDo
	Omit(cols ...field.Expr) IProductSpecDo
	Join(table schema.Tabler, on ...field.Expr) IProductSpecDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo
	Group(cols ...field.Expr) IProductSpecDo
	Having(conds ...gen.Condition) IProductSpecDo
	Limit(limit int) IProductSpecDo
	Offset(offset int) IProductSpecDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpecDo
	Unscoped() IProductSpecDo
	Create(values ...*quote_manage.ProductSpec) error
	CreateInBatches(values []*quote_manage.ProductSpec, batchSize int) error
	Save(values ...*quote_manage.ProductSpec) error
	First() (*quote_manage.ProductSpec, error)
	Take() (*quote_manage.ProductSpec, error)
	Last() (*quote_manage.ProductSpec, error)
	Find() ([]*quote_manage.ProductSpec, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.ProductSpec, err error)
	FindInBatches(result *[]*quote_manage.ProductSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.ProductSpec) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductSpecDo
	Assign(attrs ...field.AssignExpr) IProductSpecDo
	Joins(fields ...field.RelationField) IProductSpecDo
	Preload(fields ...field.RelationField) IProductSpecDo
	FirstOrInit() (*quote_manage.ProductSpec, error)
	FirstOrCreate() (*quote_manage.ProductSpec, error)
	FindByPage(offset int, limit int) (result []*quote_manage.ProductSpec, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductSpecDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productSpecDo) Debug() IProductSpecDo {
	return p.withDO(p.DO.Debug())
}

func (p productSpecDo) WithContext(ctx context.Context) IProductSpecDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productSpecDo) ReadDB() IProductSpecDo {
	return p.Clauses(dbresolver.Read)
}

func (p productSpecDo) WriteDB() IProductSpecDo {
	return p.Clauses(dbresolver.Write)
}

func (p productSpecDo) Session(config *gorm.Session) IProductSpecDo {
	return p.withDO(p.DO.Session(config))
}

func (p productSpecDo) Clauses(conds ...clause.Expression) IProductSpecDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productSpecDo) Returning(value interface{}, columns ...string) IProductSpecDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productSpecDo) Not(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productSpecDo) Or(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productSpecDo) Select(conds ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productSpecDo) Where(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productSpecDo) Order(conds ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productSpecDo) Distinct(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productSpecDo) Omit(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productSpecDo) Join(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productSpecDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productSpecDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productSpecDo) Group(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productSpecDo) Having(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productSpecDo) Limit(limit int) IProductSpecDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productSpecDo) Offset(offset int) IProductSpecDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productSpecDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpecDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productSpecDo) Unscoped() IProductSpecDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productSpecDo) Create(values ...*quote_manage.ProductSpec) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productSpecDo) CreateInBatches(values []*quote_manage.ProductSpec, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productSpecDo) Save(values ...*quote_manage.ProductSpec) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productSpecDo) First() (*quote_manage.ProductSpec, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.ProductSpec), nil
	}
}

func (p productSpecDo) Take() (*quote_manage.ProductSpec, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.ProductSpec), nil
	}
}

func (p productSpecDo) Last() (*quote_manage.ProductSpec, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.ProductSpec), nil
	}
}

func (p productSpecDo) Find() ([]*quote_manage.ProductSpec, error) {
	result, err := p.DO.Find()
	return result.([]*quote_manage.ProductSpec), err
}

func (p productSpecDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.ProductSpec, err error) {
	buf := make([]*quote_manage.ProductSpec, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productSpecDo) FindInBatches(result *[]*quote_manage.ProductSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productSpecDo) Attrs(attrs ...field.AssignExpr) IProductSpecDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productSpecDo) Assign(attrs ...field.AssignExpr) IProductSpecDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productSpecDo) Joins(fields ...field.RelationField) IProductSpecDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productSpecDo) Preload(fields ...field.RelationField) IProductSpecDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productSpecDo) FirstOrInit() (*quote_manage.ProductSpec, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.ProductSpec), nil
	}
}

func (p productSpecDo) FirstOrCreate() (*quote_manage.ProductSpec, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.ProductSpec), nil
	}
}

func (p productSpecDo) FindByPage(offset int, limit int) (result []*quote_manage.ProductSpec, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productSpecDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productSpecDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productSpecDo) Delete(models ...*quote_manage.ProductSpec) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productSpecDo) withDO(do gen.Dao) *productSpecDo {
	p.DO = *do.(*gen.DO)
	return p
}
