// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newQuoteProcessNode(db *gorm.DB, opts ...gen.DOOption) quoteProcessNode {
	_quoteProcessNode := quoteProcessNode{}

	_quoteProcessNode.quoteProcessNodeDo.UseDB(db, opts...)
	_quoteProcessNode.quoteProcessNodeDo.UseModel(&quote_manage.QuoteProcessNode{})

	tableName := _quoteProcessNode.quoteProcessNodeDo.TableName()
	_quoteProcessNode.ALL = field.NewAsterisk(tableName)
	_quoteProcessNode.ID = field.NewInt32(tableName, "id")
	_quoteProcessNode.ProcessID = field.NewInt32(tableName, "process_id")
	_quoteProcessNode.SeqNum = field.NewInt32(tableName, "seq_num")
	_quoteProcessNode.NodeNum = field.NewInt32(tableName, "node_num")
	_quoteProcessNode.Name = field.NewString(tableName, "name")
	_quoteProcessNode.Role = field.NewString(tableName, "role")
	_quoteProcessNode.Status = field.NewString(tableName, "status")
	_quoteProcessNode.ApproverID = field.NewInt32(tableName, "approver_id")
	_quoteProcessNode.ApproverName = field.NewString(tableName, "approver_name")
	_quoteProcessNode.ApproveComment = field.NewString(tableName, "approve_comment")
	_quoteProcessNode.CreatedAt = field.NewTime(tableName, "created_at")
	_quoteProcessNode.ApproveAt = field.NewTime(tableName, "approve_at")

	_quoteProcessNode.fillFieldMap()

	return _quoteProcessNode
}

type quoteProcessNode struct {
	quoteProcessNodeDo

	ALL            field.Asterisk
	ID             field.Int32
	ProcessID      field.Int32
	SeqNum         field.Int32
	NodeNum        field.Int32
	Name           field.String
	Role           field.String
	Status         field.String
	ApproverID     field.Int32
	ApproverName   field.String
	ApproveComment field.String
	CreatedAt      field.Time
	ApproveAt      field.Time

	fieldMap map[string]field.Expr
}

func (q quoteProcessNode) Table(newTableName string) *quoteProcessNode {
	q.quoteProcessNodeDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quoteProcessNode) As(alias string) *quoteProcessNode {
	q.quoteProcessNodeDo.DO = *(q.quoteProcessNodeDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quoteProcessNode) updateTableName(table string) *quoteProcessNode {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.ProcessID = field.NewInt32(table, "process_id")
	q.SeqNum = field.NewInt32(table, "seq_num")
	q.NodeNum = field.NewInt32(table, "node_num")
	q.Name = field.NewString(table, "name")
	q.Role = field.NewString(table, "role")
	q.Status = field.NewString(table, "status")
	q.ApproverID = field.NewInt32(table, "approver_id")
	q.ApproverName = field.NewString(table, "approver_name")
	q.ApproveComment = field.NewString(table, "approve_comment")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.ApproveAt = field.NewTime(table, "approve_at")

	q.fillFieldMap()

	return q
}

func (q *quoteProcessNode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quoteProcessNode) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 12)
	q.fieldMap["id"] = q.ID
	q.fieldMap["process_id"] = q.ProcessID
	q.fieldMap["seq_num"] = q.SeqNum
	q.fieldMap["node_num"] = q.NodeNum
	q.fieldMap["name"] = q.Name
	q.fieldMap["role"] = q.Role
	q.fieldMap["status"] = q.Status
	q.fieldMap["approver_id"] = q.ApproverID
	q.fieldMap["approver_name"] = q.ApproverName
	q.fieldMap["approve_comment"] = q.ApproveComment
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["approve_at"] = q.ApproveAt
}

func (q quoteProcessNode) clone(db *gorm.DB) quoteProcessNode {
	q.quoteProcessNodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quoteProcessNode) replaceDB(db *gorm.DB) quoteProcessNode {
	q.quoteProcessNodeDo.ReplaceDB(db)
	return q
}

type quoteProcessNodeDo struct{ gen.DO }

type IQuoteProcessNodeDo interface {
	gen.SubQuery
	Debug() IQuoteProcessNodeDo
	WithContext(ctx context.Context) IQuoteProcessNodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuoteProcessNodeDo
	WriteDB() IQuoteProcessNodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuoteProcessNodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuoteProcessNodeDo
	Not(conds ...gen.Condition) IQuoteProcessNodeDo
	Or(conds ...gen.Condition) IQuoteProcessNodeDo
	Select(conds ...field.Expr) IQuoteProcessNodeDo
	Where(conds ...gen.Condition) IQuoteProcessNodeDo
	Order(conds ...field.Expr) IQuoteProcessNodeDo
	Distinct(cols ...field.Expr) IQuoteProcessNodeDo
	Omit(cols ...field.Expr) IQuoteProcessNodeDo
	Join(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo
	Group(cols ...field.Expr) IQuoteProcessNodeDo
	Having(conds ...gen.Condition) IQuoteProcessNodeDo
	Limit(limit int) IQuoteProcessNodeDo
	Offset(offset int) IQuoteProcessNodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteProcessNodeDo
	Unscoped() IQuoteProcessNodeDo
	Create(values ...*quote_manage.QuoteProcessNode) error
	CreateInBatches(values []*quote_manage.QuoteProcessNode, batchSize int) error
	Save(values ...*quote_manage.QuoteProcessNode) error
	First() (*quote_manage.QuoteProcessNode, error)
	Take() (*quote_manage.QuoteProcessNode, error)
	Last() (*quote_manage.QuoteProcessNode, error)
	Find() ([]*quote_manage.QuoteProcessNode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.QuoteProcessNode, err error)
	FindInBatches(result *[]*quote_manage.QuoteProcessNode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.QuoteProcessNode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuoteProcessNodeDo
	Assign(attrs ...field.AssignExpr) IQuoteProcessNodeDo
	Joins(fields ...field.RelationField) IQuoteProcessNodeDo
	Preload(fields ...field.RelationField) IQuoteProcessNodeDo
	FirstOrInit() (*quote_manage.QuoteProcessNode, error)
	FirstOrCreate() (*quote_manage.QuoteProcessNode, error)
	FindByPage(offset int, limit int) (result []*quote_manage.QuoteProcessNode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuoteProcessNodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quoteProcessNodeDo) Debug() IQuoteProcessNodeDo {
	return q.withDO(q.DO.Debug())
}

func (q quoteProcessNodeDo) WithContext(ctx context.Context) IQuoteProcessNodeDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quoteProcessNodeDo) ReadDB() IQuoteProcessNodeDo {
	return q.Clauses(dbresolver.Read)
}

func (q quoteProcessNodeDo) WriteDB() IQuoteProcessNodeDo {
	return q.Clauses(dbresolver.Write)
}

func (q quoteProcessNodeDo) Session(config *gorm.Session) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Session(config))
}

func (q quoteProcessNodeDo) Clauses(conds ...clause.Expression) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quoteProcessNodeDo) Returning(value interface{}, columns ...string) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quoteProcessNodeDo) Not(conds ...gen.Condition) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quoteProcessNodeDo) Or(conds ...gen.Condition) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quoteProcessNodeDo) Select(conds ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quoteProcessNodeDo) Where(conds ...gen.Condition) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quoteProcessNodeDo) Order(conds ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quoteProcessNodeDo) Distinct(cols ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quoteProcessNodeDo) Omit(cols ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quoteProcessNodeDo) Join(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quoteProcessNodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quoteProcessNodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quoteProcessNodeDo) Group(cols ...field.Expr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quoteProcessNodeDo) Having(conds ...gen.Condition) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quoteProcessNodeDo) Limit(limit int) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quoteProcessNodeDo) Offset(offset int) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quoteProcessNodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quoteProcessNodeDo) Unscoped() IQuoteProcessNodeDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quoteProcessNodeDo) Create(values ...*quote_manage.QuoteProcessNode) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quoteProcessNodeDo) CreateInBatches(values []*quote_manage.QuoteProcessNode, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quoteProcessNodeDo) Save(values ...*quote_manage.QuoteProcessNode) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quoteProcessNodeDo) First() (*quote_manage.QuoteProcessNode, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcessNode), nil
	}
}

func (q quoteProcessNodeDo) Take() (*quote_manage.QuoteProcessNode, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcessNode), nil
	}
}

func (q quoteProcessNodeDo) Last() (*quote_manage.QuoteProcessNode, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcessNode), nil
	}
}

func (q quoteProcessNodeDo) Find() ([]*quote_manage.QuoteProcessNode, error) {
	result, err := q.DO.Find()
	return result.([]*quote_manage.QuoteProcessNode), err
}

func (q quoteProcessNodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.QuoteProcessNode, err error) {
	buf := make([]*quote_manage.QuoteProcessNode, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quoteProcessNodeDo) FindInBatches(result *[]*quote_manage.QuoteProcessNode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quoteProcessNodeDo) Attrs(attrs ...field.AssignExpr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quoteProcessNodeDo) Assign(attrs ...field.AssignExpr) IQuoteProcessNodeDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quoteProcessNodeDo) Joins(fields ...field.RelationField) IQuoteProcessNodeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quoteProcessNodeDo) Preload(fields ...field.RelationField) IQuoteProcessNodeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quoteProcessNodeDo) FirstOrInit() (*quote_manage.QuoteProcessNode, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcessNode), nil
	}
}

func (q quoteProcessNodeDo) FirstOrCreate() (*quote_manage.QuoteProcessNode, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.QuoteProcessNode), nil
	}
}

func (q quoteProcessNodeDo) FindByPage(offset int, limit int) (result []*quote_manage.QuoteProcessNode, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quoteProcessNodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quoteProcessNodeDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quoteProcessNodeDo) Delete(models ...*quote_manage.QuoteProcessNode) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quoteProcessNodeDo) withDO(do gen.Dao) *quoteProcessNodeDo {
	q.DO = *do.(*gen.DO)
	return q
}
