// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newCostWorksheet(db *gorm.DB, opts ...gen.DOOption) costWorksheet {
	_costWorksheet := costWorksheet{}

	_costWorksheet.costWorksheetDo.UseDB(db, opts...)
	_costWorksheet.costWorksheetDo.UseModel(&quote_manage.CostWorksheet{})

	tableName := _costWorksheet.costWorksheetDo.TableName()
	_costWorksheet.ALL = field.NewAsterisk(tableName)
	_costWorksheet.ID = field.NewInt32(tableName, "id")
	_costWorksheet.SpecID = field.NewInt32(tableName, "spec_id")
	_costWorksheet.MaterialCost = field.NewFloat64(tableName, "material_cost")
	_costWorksheet.LaborCost = field.NewFloat64(tableName, "labor_cost")
	_costWorksheet.VariOverhead = field.NewFloat64(tableName, "vari_overhead")
	_costWorksheet.FixedOverhead = field.NewFloat64(tableName, "fixed_overhead")
	_costWorksheet.FixedOverheadTiered = field.NewFloat64(tableName, "fixed_overhead_tiered")
	_costWorksheet.PeriodExpense = field.NewFloat64(tableName, "period_expense")
	_costWorksheet.TargetProfitRate = field.NewFloat64(tableName, "target_profit_rate")
	_costWorksheet.TargetProfit = field.NewFloat64(tableName, "target_profit")
	_costWorksheet.VatAmount = field.NewFloat64(tableName, "vat_amount")

	_costWorksheet.fillFieldMap()

	return _costWorksheet
}

type costWorksheet struct {
	costWorksheetDo

	ALL                 field.Asterisk
	ID                  field.Int32
	SpecID              field.Int32
	MaterialCost        field.Float64
	LaborCost           field.Float64
	VariOverhead        field.Float64
	FixedOverhead       field.Float64
	FixedOverheadTiered field.Float64
	PeriodExpense       field.Float64
	TargetProfitRate    field.Float64
	TargetProfit        field.Float64
	VatAmount           field.Float64

	fieldMap map[string]field.Expr
}

func (c costWorksheet) Table(newTableName string) *costWorksheet {
	c.costWorksheetDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c costWorksheet) As(alias string) *costWorksheet {
	c.costWorksheetDo.DO = *(c.costWorksheetDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *costWorksheet) updateTableName(table string) *costWorksheet {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.SpecID = field.NewInt32(table, "spec_id")
	c.MaterialCost = field.NewFloat64(table, "material_cost")
	c.LaborCost = field.NewFloat64(table, "labor_cost")
	c.VariOverhead = field.NewFloat64(table, "vari_overhead")
	c.FixedOverhead = field.NewFloat64(table, "fixed_overhead")
	c.FixedOverheadTiered = field.NewFloat64(table, "fixed_overhead_tiered")
	c.PeriodExpense = field.NewFloat64(table, "period_expense")
	c.TargetProfitRate = field.NewFloat64(table, "target_profit_rate")
	c.TargetProfit = field.NewFloat64(table, "target_profit")
	c.VatAmount = field.NewFloat64(table, "vat_amount")

	c.fillFieldMap()

	return c
}

func (c *costWorksheet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *costWorksheet) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["spec_id"] = c.SpecID
	c.fieldMap["material_cost"] = c.MaterialCost
	c.fieldMap["labor_cost"] = c.LaborCost
	c.fieldMap["vari_overhead"] = c.VariOverhead
	c.fieldMap["fixed_overhead"] = c.FixedOverhead
	c.fieldMap["fixed_overhead_tiered"] = c.FixedOverheadTiered
	c.fieldMap["period_expense"] = c.PeriodExpense
	c.fieldMap["target_profit_rate"] = c.TargetProfitRate
	c.fieldMap["target_profit"] = c.TargetProfit
	c.fieldMap["vat_amount"] = c.VatAmount
}

func (c costWorksheet) clone(db *gorm.DB) costWorksheet {
	c.costWorksheetDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c costWorksheet) replaceDB(db *gorm.DB) costWorksheet {
	c.costWorksheetDo.ReplaceDB(db)
	return c
}

type costWorksheetDo struct{ gen.DO }

type ICostWorksheetDo interface {
	gen.SubQuery
	Debug() ICostWorksheetDo
	WithContext(ctx context.Context) ICostWorksheetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICostWorksheetDo
	WriteDB() ICostWorksheetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICostWorksheetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICostWorksheetDo
	Not(conds ...gen.Condition) ICostWorksheetDo
	Or(conds ...gen.Condition) ICostWorksheetDo
	Select(conds ...field.Expr) ICostWorksheetDo
	Where(conds ...gen.Condition) ICostWorksheetDo
	Order(conds ...field.Expr) ICostWorksheetDo
	Distinct(cols ...field.Expr) ICostWorksheetDo
	Omit(cols ...field.Expr) ICostWorksheetDo
	Join(table schema.Tabler, on ...field.Expr) ICostWorksheetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICostWorksheetDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICostWorksheetDo
	Group(cols ...field.Expr) ICostWorksheetDo
	Having(conds ...gen.Condition) ICostWorksheetDo
	Limit(limit int) ICostWorksheetDo
	Offset(offset int) ICostWorksheetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICostWorksheetDo
	Unscoped() ICostWorksheetDo
	Create(values ...*quote_manage.CostWorksheet) error
	CreateInBatches(values []*quote_manage.CostWorksheet, batchSize int) error
	Save(values ...*quote_manage.CostWorksheet) error
	First() (*quote_manage.CostWorksheet, error)
	Take() (*quote_manage.CostWorksheet, error)
	Last() (*quote_manage.CostWorksheet, error)
	Find() ([]*quote_manage.CostWorksheet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.CostWorksheet, err error)
	FindInBatches(result *[]*quote_manage.CostWorksheet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.CostWorksheet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICostWorksheetDo
	Assign(attrs ...field.AssignExpr) ICostWorksheetDo
	Joins(fields ...field.RelationField) ICostWorksheetDo
	Preload(fields ...field.RelationField) ICostWorksheetDo
	FirstOrInit() (*quote_manage.CostWorksheet, error)
	FirstOrCreate() (*quote_manage.CostWorksheet, error)
	FindByPage(offset int, limit int) (result []*quote_manage.CostWorksheet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICostWorksheetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c costWorksheetDo) Debug() ICostWorksheetDo {
	return c.withDO(c.DO.Debug())
}

func (c costWorksheetDo) WithContext(ctx context.Context) ICostWorksheetDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c costWorksheetDo) ReadDB() ICostWorksheetDo {
	return c.Clauses(dbresolver.Read)
}

func (c costWorksheetDo) WriteDB() ICostWorksheetDo {
	return c.Clauses(dbresolver.Write)
}

func (c costWorksheetDo) Session(config *gorm.Session) ICostWorksheetDo {
	return c.withDO(c.DO.Session(config))
}

func (c costWorksheetDo) Clauses(conds ...clause.Expression) ICostWorksheetDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c costWorksheetDo) Returning(value interface{}, columns ...string) ICostWorksheetDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c costWorksheetDo) Not(conds ...gen.Condition) ICostWorksheetDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c costWorksheetDo) Or(conds ...gen.Condition) ICostWorksheetDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c costWorksheetDo) Select(conds ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c costWorksheetDo) Where(conds ...gen.Condition) ICostWorksheetDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c costWorksheetDo) Order(conds ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c costWorksheetDo) Distinct(cols ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c costWorksheetDo) Omit(cols ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c costWorksheetDo) Join(table schema.Tabler, on ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c costWorksheetDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c costWorksheetDo) RightJoin(table schema.Tabler, on ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c costWorksheetDo) Group(cols ...field.Expr) ICostWorksheetDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c costWorksheetDo) Having(conds ...gen.Condition) ICostWorksheetDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c costWorksheetDo) Limit(limit int) ICostWorksheetDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c costWorksheetDo) Offset(offset int) ICostWorksheetDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c costWorksheetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICostWorksheetDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c costWorksheetDo) Unscoped() ICostWorksheetDo {
	return c.withDO(c.DO.Unscoped())
}

func (c costWorksheetDo) Create(values ...*quote_manage.CostWorksheet) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c costWorksheetDo) CreateInBatches(values []*quote_manage.CostWorksheet, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c costWorksheetDo) Save(values ...*quote_manage.CostWorksheet) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c costWorksheetDo) First() (*quote_manage.CostWorksheet, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.CostWorksheet), nil
	}
}

func (c costWorksheetDo) Take() (*quote_manage.CostWorksheet, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.CostWorksheet), nil
	}
}

func (c costWorksheetDo) Last() (*quote_manage.CostWorksheet, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.CostWorksheet), nil
	}
}

func (c costWorksheetDo) Find() ([]*quote_manage.CostWorksheet, error) {
	result, err := c.DO.Find()
	return result.([]*quote_manage.CostWorksheet), err
}

func (c costWorksheetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.CostWorksheet, err error) {
	buf := make([]*quote_manage.CostWorksheet, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c costWorksheetDo) FindInBatches(result *[]*quote_manage.CostWorksheet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c costWorksheetDo) Attrs(attrs ...field.AssignExpr) ICostWorksheetDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c costWorksheetDo) Assign(attrs ...field.AssignExpr) ICostWorksheetDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c costWorksheetDo) Joins(fields ...field.RelationField) ICostWorksheetDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c costWorksheetDo) Preload(fields ...field.RelationField) ICostWorksheetDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c costWorksheetDo) FirstOrInit() (*quote_manage.CostWorksheet, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.CostWorksheet), nil
	}
}

func (c costWorksheetDo) FirstOrCreate() (*quote_manage.CostWorksheet, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.CostWorksheet), nil
	}
}

func (c costWorksheetDo) FindByPage(offset int, limit int) (result []*quote_manage.CostWorksheet, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c costWorksheetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c costWorksheetDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c costWorksheetDo) Delete(models ...*quote_manage.CostWorksheet) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *costWorksheetDo) withDO(do gen.Dao) *costWorksheetDo {
	c.DO = *do.(*gen.DO)
	return c
}
