// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/quote_manage"
)

func newQuote(db *gorm.DB, opts ...gen.DOOption) quote {
	_quote := quote{}

	_quote.quoteDo.UseDB(db, opts...)
	_quote.quoteDo.UseModel(&quote_manage.Quote{})

	tableName := _quote.quoteDo.TableName()
	_quote.ALL = field.NewAsterisk(tableName)
	_quote.ID = field.NewInt32(tableName, "id")
	_quote.QuoteCode = field.NewString(tableName, "quote_code")
	_quote.CustomerID = field.NewInt32(tableName, "customer_id")
	_quote.CustomerName = field.NewString(tableName, "customer_name")
	_quote.ContactName = field.NewString(tableName, "contact_name")
	_quote.ContactTitle = field.NewString(tableName, "contact_title")
	_quote.ValidDays = field.NewString(tableName, "valid_days")
	_quote.HandlerID = field.NewInt32(tableName, "handler_id")
	_quote.HandlerName = field.NewString(tableName, "handler_name")
	_quote.QuoteDate = field.NewTime(tableName, "quote_date")

	_quote.fillFieldMap()

	return _quote
}

type quote struct {
	quoteDo

	ALL          field.Asterisk
	ID           field.Int32
	QuoteCode    field.String
	CustomerID   field.Int32
	CustomerName field.String
	ContactName  field.String
	ContactTitle field.String
	ValidDays    field.String
	HandlerID    field.Int32
	HandlerName  field.String
	QuoteDate    field.Time

	fieldMap map[string]field.Expr
}

func (q quote) Table(newTableName string) *quote {
	q.quoteDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quote) As(alias string) *quote {
	q.quoteDo.DO = *(q.quoteDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quote) updateTableName(table string) *quote {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.QuoteCode = field.NewString(table, "quote_code")
	q.CustomerID = field.NewInt32(table, "customer_id")
	q.CustomerName = field.NewString(table, "customer_name")
	q.ContactName = field.NewString(table, "contact_name")
	q.ContactTitle = field.NewString(table, "contact_title")
	q.ValidDays = field.NewString(table, "valid_days")
	q.HandlerID = field.NewInt32(table, "handler_id")
	q.HandlerName = field.NewString(table, "handler_name")
	q.QuoteDate = field.NewTime(table, "quote_date")

	q.fillFieldMap()

	return q
}

func (q *quote) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quote) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 10)
	q.fieldMap["id"] = q.ID
	q.fieldMap["quote_code"] = q.QuoteCode
	q.fieldMap["customer_id"] = q.CustomerID
	q.fieldMap["customer_name"] = q.CustomerName
	q.fieldMap["contact_name"] = q.ContactName
	q.fieldMap["contact_title"] = q.ContactTitle
	q.fieldMap["valid_days"] = q.ValidDays
	q.fieldMap["handler_id"] = q.HandlerID
	q.fieldMap["handler_name"] = q.HandlerName
	q.fieldMap["quote_date"] = q.QuoteDate
}

func (q quote) clone(db *gorm.DB) quote {
	q.quoteDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quote) replaceDB(db *gorm.DB) quote {
	q.quoteDo.ReplaceDB(db)
	return q
}

type quoteDo struct{ gen.DO }

type IQuoteDo interface {
	gen.SubQuery
	Debug() IQuoteDo
	WithContext(ctx context.Context) IQuoteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuoteDo
	WriteDB() IQuoteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuoteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuoteDo
	Not(conds ...gen.Condition) IQuoteDo
	Or(conds ...gen.Condition) IQuoteDo
	Select(conds ...field.Expr) IQuoteDo
	Where(conds ...gen.Condition) IQuoteDo
	Order(conds ...field.Expr) IQuoteDo
	Distinct(cols ...field.Expr) IQuoteDo
	Omit(cols ...field.Expr) IQuoteDo
	Join(table schema.Tabler, on ...field.Expr) IQuoteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuoteDo
	Group(cols ...field.Expr) IQuoteDo
	Having(conds ...gen.Condition) IQuoteDo
	Limit(limit int) IQuoteDo
	Offset(offset int) IQuoteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteDo
	Unscoped() IQuoteDo
	Create(values ...*quote_manage.Quote) error
	CreateInBatches(values []*quote_manage.Quote, batchSize int) error
	Save(values ...*quote_manage.Quote) error
	First() (*quote_manage.Quote, error)
	Take() (*quote_manage.Quote, error)
	Last() (*quote_manage.Quote, error)
	Find() ([]*quote_manage.Quote, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.Quote, err error)
	FindInBatches(result *[]*quote_manage.Quote, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*quote_manage.Quote) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuoteDo
	Assign(attrs ...field.AssignExpr) IQuoteDo
	Joins(fields ...field.RelationField) IQuoteDo
	Preload(fields ...field.RelationField) IQuoteDo
	FirstOrInit() (*quote_manage.Quote, error)
	FirstOrCreate() (*quote_manage.Quote, error)
	FindByPage(offset int, limit int) (result []*quote_manage.Quote, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuoteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quoteDo) Debug() IQuoteDo {
	return q.withDO(q.DO.Debug())
}

func (q quoteDo) WithContext(ctx context.Context) IQuoteDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quoteDo) ReadDB() IQuoteDo {
	return q.Clauses(dbresolver.Read)
}

func (q quoteDo) WriteDB() IQuoteDo {
	return q.Clauses(dbresolver.Write)
}

func (q quoteDo) Session(config *gorm.Session) IQuoteDo {
	return q.withDO(q.DO.Session(config))
}

func (q quoteDo) Clauses(conds ...clause.Expression) IQuoteDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quoteDo) Returning(value interface{}, columns ...string) IQuoteDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quoteDo) Not(conds ...gen.Condition) IQuoteDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quoteDo) Or(conds ...gen.Condition) IQuoteDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quoteDo) Select(conds ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quoteDo) Where(conds ...gen.Condition) IQuoteDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quoteDo) Order(conds ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quoteDo) Distinct(cols ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quoteDo) Omit(cols ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quoteDo) Join(table schema.Tabler, on ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quoteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quoteDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quoteDo) Group(cols ...field.Expr) IQuoteDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quoteDo) Having(conds ...gen.Condition) IQuoteDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quoteDo) Limit(limit int) IQuoteDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quoteDo) Offset(offset int) IQuoteDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quoteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuoteDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quoteDo) Unscoped() IQuoteDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quoteDo) Create(values ...*quote_manage.Quote) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quoteDo) CreateInBatches(values []*quote_manage.Quote, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quoteDo) Save(values ...*quote_manage.Quote) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quoteDo) First() (*quote_manage.Quote, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.Quote), nil
	}
}

func (q quoteDo) Take() (*quote_manage.Quote, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.Quote), nil
	}
}

func (q quoteDo) Last() (*quote_manage.Quote, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.Quote), nil
	}
}

func (q quoteDo) Find() ([]*quote_manage.Quote, error) {
	result, err := q.DO.Find()
	return result.([]*quote_manage.Quote), err
}

func (q quoteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*quote_manage.Quote, err error) {
	buf := make([]*quote_manage.Quote, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quoteDo) FindInBatches(result *[]*quote_manage.Quote, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quoteDo) Attrs(attrs ...field.AssignExpr) IQuoteDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quoteDo) Assign(attrs ...field.AssignExpr) IQuoteDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quoteDo) Joins(fields ...field.RelationField) IQuoteDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quoteDo) Preload(fields ...field.RelationField) IQuoteDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quoteDo) FirstOrInit() (*quote_manage.Quote, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.Quote), nil
	}
}

func (q quoteDo) FirstOrCreate() (*quote_manage.Quote, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*quote_manage.Quote), nil
	}
}

func (q quoteDo) FindByPage(offset int, limit int) (result []*quote_manage.Quote, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quoteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quoteDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quoteDo) Delete(models ...*quote_manage.Quote) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quoteDo) withDO(do gen.Dao) *quoteDo {
	q.DO = *do.(*gen.DO)
	return q
}
