// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package other

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/other"
)

func newQuantityUnit(db *gorm.DB, opts ...gen.DOOption) quantityUnit {
	_quantityUnit := quantityUnit{}

	_quantityUnit.quantityUnitDo.UseDB(db, opts...)
	_quantityUnit.quantityUnitDo.UseModel(&other.QuantityUnit{})

	tableName := _quantityUnit.quantityUnitDo.TableName()
	_quantityUnit.ALL = field.NewAsterisk(tableName)
	_quantityUnit.ID = field.NewInt32(tableName, "id")
	_quantityUnit.Quantity = field.NewString(tableName, "quantity")
	_quantityUnit.Unit = field.NewString(tableName, "unit")

	_quantityUnit.fillFieldMap()

	return _quantityUnit
}

type quantityUnit struct {
	quantityUnitDo

	ALL      field.Asterisk
	ID       field.Int32
	Quantity field.String
	Unit     field.String

	fieldMap map[string]field.Expr
}

func (q quantityUnit) Table(newTableName string) *quantityUnit {
	q.quantityUnitDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quantityUnit) As(alias string) *quantityUnit {
	q.quantityUnitDo.DO = *(q.quantityUnitDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quantityUnit) updateTableName(table string) *quantityUnit {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.Quantity = field.NewString(table, "quantity")
	q.Unit = field.NewString(table, "unit")

	q.fillFieldMap()

	return q
}

func (q *quantityUnit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quantityUnit) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 3)
	q.fieldMap["id"] = q.ID
	q.fieldMap["quantity"] = q.Quantity
	q.fieldMap["unit"] = q.Unit
}

func (q quantityUnit) clone(db *gorm.DB) quantityUnit {
	q.quantityUnitDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quantityUnit) replaceDB(db *gorm.DB) quantityUnit {
	q.quantityUnitDo.ReplaceDB(db)
	return q
}

type quantityUnitDo struct{ gen.DO }

type IQuantityUnitDo interface {
	gen.SubQuery
	Debug() IQuantityUnitDo
	WithContext(ctx context.Context) IQuantityUnitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuantityUnitDo
	WriteDB() IQuantityUnitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuantityUnitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuantityUnitDo
	Not(conds ...gen.Condition) IQuantityUnitDo
	Or(conds ...gen.Condition) IQuantityUnitDo
	Select(conds ...field.Expr) IQuantityUnitDo
	Where(conds ...gen.Condition) IQuantityUnitDo
	Order(conds ...field.Expr) IQuantityUnitDo
	Distinct(cols ...field.Expr) IQuantityUnitDo
	Omit(cols ...field.Expr) IQuantityUnitDo
	Join(table schema.Tabler, on ...field.Expr) IQuantityUnitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuantityUnitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuantityUnitDo
	Group(cols ...field.Expr) IQuantityUnitDo
	Having(conds ...gen.Condition) IQuantityUnitDo
	Limit(limit int) IQuantityUnitDo
	Offset(offset int) IQuantityUnitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuantityUnitDo
	Unscoped() IQuantityUnitDo
	Create(values ...*other.QuantityUnit) error
	CreateInBatches(values []*other.QuantityUnit, batchSize int) error
	Save(values ...*other.QuantityUnit) error
	First() (*other.QuantityUnit, error)
	Take() (*other.QuantityUnit, error)
	Last() (*other.QuantityUnit, error)
	Find() ([]*other.QuantityUnit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*other.QuantityUnit, err error)
	FindInBatches(result *[]*other.QuantityUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*other.QuantityUnit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuantityUnitDo
	Assign(attrs ...field.AssignExpr) IQuantityUnitDo
	Joins(fields ...field.RelationField) IQuantityUnitDo
	Preload(fields ...field.RelationField) IQuantityUnitDo
	FirstOrInit() (*other.QuantityUnit, error)
	FirstOrCreate() (*other.QuantityUnit, error)
	FindByPage(offset int, limit int) (result []*other.QuantityUnit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuantityUnitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quantityUnitDo) Debug() IQuantityUnitDo {
	return q.withDO(q.DO.Debug())
}

func (q quantityUnitDo) WithContext(ctx context.Context) IQuantityUnitDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quantityUnitDo) ReadDB() IQuantityUnitDo {
	return q.Clauses(dbresolver.Read)
}

func (q quantityUnitDo) WriteDB() IQuantityUnitDo {
	return q.Clauses(dbresolver.Write)
}

func (q quantityUnitDo) Session(config *gorm.Session) IQuantityUnitDo {
	return q.withDO(q.DO.Session(config))
}

func (q quantityUnitDo) Clauses(conds ...clause.Expression) IQuantityUnitDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quantityUnitDo) Returning(value interface{}, columns ...string) IQuantityUnitDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quantityUnitDo) Not(conds ...gen.Condition) IQuantityUnitDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quantityUnitDo) Or(conds ...gen.Condition) IQuantityUnitDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quantityUnitDo) Select(conds ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quantityUnitDo) Where(conds ...gen.Condition) IQuantityUnitDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quantityUnitDo) Order(conds ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quantityUnitDo) Distinct(cols ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quantityUnitDo) Omit(cols ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quantityUnitDo) Join(table schema.Tabler, on ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quantityUnitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quantityUnitDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quantityUnitDo) Group(cols ...field.Expr) IQuantityUnitDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quantityUnitDo) Having(conds ...gen.Condition) IQuantityUnitDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quantityUnitDo) Limit(limit int) IQuantityUnitDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quantityUnitDo) Offset(offset int) IQuantityUnitDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quantityUnitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuantityUnitDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quantityUnitDo) Unscoped() IQuantityUnitDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quantityUnitDo) Create(values ...*other.QuantityUnit) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quantityUnitDo) CreateInBatches(values []*other.QuantityUnit, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quantityUnitDo) Save(values ...*other.QuantityUnit) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quantityUnitDo) First() (*other.QuantityUnit, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*other.QuantityUnit), nil
	}
}

func (q quantityUnitDo) Take() (*other.QuantityUnit, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*other.QuantityUnit), nil
	}
}

func (q quantityUnitDo) Last() (*other.QuantityUnit, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*other.QuantityUnit), nil
	}
}

func (q quantityUnitDo) Find() ([]*other.QuantityUnit, error) {
	result, err := q.DO.Find()
	return result.([]*other.QuantityUnit), err
}

func (q quantityUnitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*other.QuantityUnit, err error) {
	buf := make([]*other.QuantityUnit, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quantityUnitDo) FindInBatches(result *[]*other.QuantityUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quantityUnitDo) Attrs(attrs ...field.AssignExpr) IQuantityUnitDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quantityUnitDo) Assign(attrs ...field.AssignExpr) IQuantityUnitDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quantityUnitDo) Joins(fields ...field.RelationField) IQuantityUnitDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quantityUnitDo) Preload(fields ...field.RelationField) IQuantityUnitDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quantityUnitDo) FirstOrInit() (*other.QuantityUnit, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*other.QuantityUnit), nil
	}
}

func (q quantityUnitDo) FirstOrCreate() (*other.QuantityUnit, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*other.QuantityUnit), nil
	}
}

func (q quantityUnitDo) FindByPage(offset int, limit int) (result []*other.QuantityUnit, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quantityUnitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quantityUnitDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quantityUnitDo) Delete(models ...*other.QuantityUnit) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quantityUnitDo) withDO(do gen.Dao) *quantityUnitDo {
	q.DO = *do.(*gen.DO)
	return q
}
