// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package other

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/other"
)

func newValueLabel(db *gorm.DB, opts ...gen.DOOption) valueLabel {
	_valueLabel := valueLabel{}

	_valueLabel.valueLabelDo.UseDB(db, opts...)
	_valueLabel.valueLabelDo.UseModel(&other.ValueLabel{})

	tableName := _valueLabel.valueLabelDo.TableName()
	_valueLabel.ALL = field.NewAsterisk(tableName)
	_valueLabel.ID = field.NewInt32(tableName, "id")
	_valueLabel.Value = field.NewString(tableName, "value")
	_valueLabel.Label = field.NewString(tableName, "label")

	_valueLabel.fillFieldMap()

	return _valueLabel
}

type valueLabel struct {
	valueLabelDo

	ALL   field.Asterisk
	ID    field.Int32
	Value field.String
	Label field.String

	fieldMap map[string]field.Expr
}

func (v valueLabel) Table(newTableName string) *valueLabel {
	v.valueLabelDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v valueLabel) As(alias string) *valueLabel {
	v.valueLabelDo.DO = *(v.valueLabelDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *valueLabel) updateTableName(table string) *valueLabel {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt32(table, "id")
	v.Value = field.NewString(table, "value")
	v.Label = field.NewString(table, "label")

	v.fillFieldMap()

	return v
}

func (v *valueLabel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *valueLabel) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 3)
	v.fieldMap["id"] = v.ID
	v.fieldMap["value"] = v.Value
	v.fieldMap["label"] = v.Label
}

func (v valueLabel) clone(db *gorm.DB) valueLabel {
	v.valueLabelDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v valueLabel) replaceDB(db *gorm.DB) valueLabel {
	v.valueLabelDo.ReplaceDB(db)
	return v
}

type valueLabelDo struct{ gen.DO }

type IValueLabelDo interface {
	gen.SubQuery
	Debug() IValueLabelDo
	WithContext(ctx context.Context) IValueLabelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IValueLabelDo
	WriteDB() IValueLabelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IValueLabelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IValueLabelDo
	Not(conds ...gen.Condition) IValueLabelDo
	Or(conds ...gen.Condition) IValueLabelDo
	Select(conds ...field.Expr) IValueLabelDo
	Where(conds ...gen.Condition) IValueLabelDo
	Order(conds ...field.Expr) IValueLabelDo
	Distinct(cols ...field.Expr) IValueLabelDo
	Omit(cols ...field.Expr) IValueLabelDo
	Join(table schema.Tabler, on ...field.Expr) IValueLabelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IValueLabelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IValueLabelDo
	Group(cols ...field.Expr) IValueLabelDo
	Having(conds ...gen.Condition) IValueLabelDo
	Limit(limit int) IValueLabelDo
	Offset(offset int) IValueLabelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IValueLabelDo
	Unscoped() IValueLabelDo
	Create(values ...*other.ValueLabel) error
	CreateInBatches(values []*other.ValueLabel, batchSize int) error
	Save(values ...*other.ValueLabel) error
	First() (*other.ValueLabel, error)
	Take() (*other.ValueLabel, error)
	Last() (*other.ValueLabel, error)
	Find() ([]*other.ValueLabel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*other.ValueLabel, err error)
	FindInBatches(result *[]*other.ValueLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*other.ValueLabel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IValueLabelDo
	Assign(attrs ...field.AssignExpr) IValueLabelDo
	Joins(fields ...field.RelationField) IValueLabelDo
	Preload(fields ...field.RelationField) IValueLabelDo
	FirstOrInit() (*other.ValueLabel, error)
	FirstOrCreate() (*other.ValueLabel, error)
	FindByPage(offset int, limit int) (result []*other.ValueLabel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IValueLabelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v valueLabelDo) Debug() IValueLabelDo {
	return v.withDO(v.DO.Debug())
}

func (v valueLabelDo) WithContext(ctx context.Context) IValueLabelDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v valueLabelDo) ReadDB() IValueLabelDo {
	return v.Clauses(dbresolver.Read)
}

func (v valueLabelDo) WriteDB() IValueLabelDo {
	return v.Clauses(dbresolver.Write)
}

func (v valueLabelDo) Session(config *gorm.Session) IValueLabelDo {
	return v.withDO(v.DO.Session(config))
}

func (v valueLabelDo) Clauses(conds ...clause.Expression) IValueLabelDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v valueLabelDo) Returning(value interface{}, columns ...string) IValueLabelDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v valueLabelDo) Not(conds ...gen.Condition) IValueLabelDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v valueLabelDo) Or(conds ...gen.Condition) IValueLabelDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v valueLabelDo) Select(conds ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v valueLabelDo) Where(conds ...gen.Condition) IValueLabelDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v valueLabelDo) Order(conds ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v valueLabelDo) Distinct(cols ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v valueLabelDo) Omit(cols ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v valueLabelDo) Join(table schema.Tabler, on ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v valueLabelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v valueLabelDo) RightJoin(table schema.Tabler, on ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v valueLabelDo) Group(cols ...field.Expr) IValueLabelDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v valueLabelDo) Having(conds ...gen.Condition) IValueLabelDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v valueLabelDo) Limit(limit int) IValueLabelDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v valueLabelDo) Offset(offset int) IValueLabelDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v valueLabelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IValueLabelDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v valueLabelDo) Unscoped() IValueLabelDo {
	return v.withDO(v.DO.Unscoped())
}

func (v valueLabelDo) Create(values ...*other.ValueLabel) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v valueLabelDo) CreateInBatches(values []*other.ValueLabel, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v valueLabelDo) Save(values ...*other.ValueLabel) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v valueLabelDo) First() (*other.ValueLabel, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*other.ValueLabel), nil
	}
}

func (v valueLabelDo) Take() (*other.ValueLabel, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*other.ValueLabel), nil
	}
}

func (v valueLabelDo) Last() (*other.ValueLabel, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*other.ValueLabel), nil
	}
}

func (v valueLabelDo) Find() ([]*other.ValueLabel, error) {
	result, err := v.DO.Find()
	return result.([]*other.ValueLabel), err
}

func (v valueLabelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*other.ValueLabel, err error) {
	buf := make([]*other.ValueLabel, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v valueLabelDo) FindInBatches(result *[]*other.ValueLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v valueLabelDo) Attrs(attrs ...field.AssignExpr) IValueLabelDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v valueLabelDo) Assign(attrs ...field.AssignExpr) IValueLabelDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v valueLabelDo) Joins(fields ...field.RelationField) IValueLabelDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v valueLabelDo) Preload(fields ...field.RelationField) IValueLabelDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v valueLabelDo) FirstOrInit() (*other.ValueLabel, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*other.ValueLabel), nil
	}
}

func (v valueLabelDo) FirstOrCreate() (*other.ValueLabel, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*other.ValueLabel), nil
	}
}

func (v valueLabelDo) FindByPage(offset int, limit int) (result []*other.ValueLabel, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v valueLabelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v valueLabelDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v valueLabelDo) Delete(models ...*other.ValueLabel) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *valueLabelDo) withDO(do gen.Dao) *valueLabelDo {
	v.DO = *do.(*gen.DO)
	return v
}
