// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuoteEmployee = "quote_employee"

// QuoteEmployee mapped from table <quote_employee>
type QuoteEmployee struct {
	ID         int32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID *int32 `gorm:"column:employee_id;type:int unsigned;index:employee,priority:1" json:"employee_id"`
}

// TableName QuoteEmployee's table name
func (*QuoteEmployee) TableName() string {
	return TableNameQuoteEmployee
}
