// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		PriceCatalog:    newPriceCatalog(db, opts...),
		ProductCategory: newProductCategory(db, opts...),
		ProductSku:      newProductSku(db, opts...),
		ProductSpu:      newProductSpu(db, opts...),
		Shape:           newShape(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	PriceCatalog    priceCatalog
	ProductCategory productCategory
	ProductSku      productSku
	ProductSpu      productSpu
	Shape           shape
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		PriceCatalog:    q.PriceCatalog.clone(db),
		ProductCategory: q.ProductCategory.clone(db),
		ProductSku:      q.ProductSku.clone(db),
		ProductSpu:      q.ProductSpu.clone(db),
		Shape:           q.Shape.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		PriceCatalog:    q.PriceCatalog.replaceDB(db),
		ProductCategory: q.ProductCategory.replaceDB(db),
		ProductSku:      q.ProductSku.replaceDB(db),
		ProductSpu:      q.ProductSpu.replaceDB(db),
		Shape:           q.Shape.replaceDB(db),
	}
}

type queryCtx struct {
	PriceCatalog    IPriceCatalogDo
	ProductCategory IProductCategoryDo
	ProductSku      IProductSkuDo
	ProductSpu      IProductSpuDo
	Shape           IShapeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		PriceCatalog:    q.PriceCatalog.WithContext(ctx),
		ProductCategory: q.ProductCategory.WithContext(ctx),
		ProductSku:      q.ProductSku.WithContext(ctx),
		ProductSpu:      q.ProductSpu.WithContext(ctx),
		Shape:           q.Shape.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
