// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/product"
)

func newPriceCatalog(db *gorm.DB, opts ...gen.DOOption) priceCatalog {
	_priceCatalog := priceCatalog{}

	_priceCatalog.priceCatalogDo.UseDB(db, opts...)
	_priceCatalog.priceCatalogDo.UseModel(&product.PriceCatalog{})

	tableName := _priceCatalog.priceCatalogDo.TableName()
	_priceCatalog.ALL = field.NewAsterisk(tableName)
	_priceCatalog.ID = field.NewInt32(tableName, "id")
	_priceCatalog.SkuID = field.NewInt32(tableName, "sku_id")
	_priceCatalog.Price = field.NewFloat64(tableName, "price")

	_priceCatalog.fillFieldMap()

	return _priceCatalog
}

type priceCatalog struct {
	priceCatalogDo

	ALL   field.Asterisk
	ID    field.Int32
	SkuID field.Int32
	Price field.Float64

	fieldMap map[string]field.Expr
}

func (p priceCatalog) Table(newTableName string) *priceCatalog {
	p.priceCatalogDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p priceCatalog) As(alias string) *priceCatalog {
	p.priceCatalogDo.DO = *(p.priceCatalogDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *priceCatalog) updateTableName(table string) *priceCatalog {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.SkuID = field.NewInt32(table, "sku_id")
	p.Price = field.NewFloat64(table, "price")

	p.fillFieldMap()

	return p
}

func (p *priceCatalog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *priceCatalog) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["sku_id"] = p.SkuID
	p.fieldMap["price"] = p.Price
}

func (p priceCatalog) clone(db *gorm.DB) priceCatalog {
	p.priceCatalogDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p priceCatalog) replaceDB(db *gorm.DB) priceCatalog {
	p.priceCatalogDo.ReplaceDB(db)
	return p
}

type priceCatalogDo struct{ gen.DO }

type IPriceCatalogDo interface {
	gen.SubQuery
	Debug() IPriceCatalogDo
	WithContext(ctx context.Context) IPriceCatalogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPriceCatalogDo
	WriteDB() IPriceCatalogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPriceCatalogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPriceCatalogDo
	Not(conds ...gen.Condition) IPriceCatalogDo
	Or(conds ...gen.Condition) IPriceCatalogDo
	Select(conds ...field.Expr) IPriceCatalogDo
	Where(conds ...gen.Condition) IPriceCatalogDo
	Order(conds ...field.Expr) IPriceCatalogDo
	Distinct(cols ...field.Expr) IPriceCatalogDo
	Omit(cols ...field.Expr) IPriceCatalogDo
	Join(table schema.Tabler, on ...field.Expr) IPriceCatalogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPriceCatalogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPriceCatalogDo
	Group(cols ...field.Expr) IPriceCatalogDo
	Having(conds ...gen.Condition) IPriceCatalogDo
	Limit(limit int) IPriceCatalogDo
	Offset(offset int) IPriceCatalogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPriceCatalogDo
	Unscoped() IPriceCatalogDo
	Create(values ...*product.PriceCatalog) error
	CreateInBatches(values []*product.PriceCatalog, batchSize int) error
	Save(values ...*product.PriceCatalog) error
	First() (*product.PriceCatalog, error)
	Take() (*product.PriceCatalog, error)
	Last() (*product.PriceCatalog, error)
	Find() ([]*product.PriceCatalog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.PriceCatalog, err error)
	FindInBatches(result *[]*product.PriceCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.PriceCatalog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPriceCatalogDo
	Assign(attrs ...field.AssignExpr) IPriceCatalogDo
	Joins(fields ...field.RelationField) IPriceCatalogDo
	Preload(fields ...field.RelationField) IPriceCatalogDo
	FirstOrInit() (*product.PriceCatalog, error)
	FirstOrCreate() (*product.PriceCatalog, error)
	FindByPage(offset int, limit int) (result []*product.PriceCatalog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPriceCatalogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p priceCatalogDo) Debug() IPriceCatalogDo {
	return p.withDO(p.DO.Debug())
}

func (p priceCatalogDo) WithContext(ctx context.Context) IPriceCatalogDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p priceCatalogDo) ReadDB() IPriceCatalogDo {
	return p.Clauses(dbresolver.Read)
}

func (p priceCatalogDo) WriteDB() IPriceCatalogDo {
	return p.Clauses(dbresolver.Write)
}

func (p priceCatalogDo) Session(config *gorm.Session) IPriceCatalogDo {
	return p.withDO(p.DO.Session(config))
}

func (p priceCatalogDo) Clauses(conds ...clause.Expression) IPriceCatalogDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p priceCatalogDo) Returning(value interface{}, columns ...string) IPriceCatalogDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p priceCatalogDo) Not(conds ...gen.Condition) IPriceCatalogDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p priceCatalogDo) Or(conds ...gen.Condition) IPriceCatalogDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p priceCatalogDo) Select(conds ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p priceCatalogDo) Where(conds ...gen.Condition) IPriceCatalogDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p priceCatalogDo) Order(conds ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p priceCatalogDo) Distinct(cols ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p priceCatalogDo) Omit(cols ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p priceCatalogDo) Join(table schema.Tabler, on ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p priceCatalogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p priceCatalogDo) RightJoin(table schema.Tabler, on ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p priceCatalogDo) Group(cols ...field.Expr) IPriceCatalogDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p priceCatalogDo) Having(conds ...gen.Condition) IPriceCatalogDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p priceCatalogDo) Limit(limit int) IPriceCatalogDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p priceCatalogDo) Offset(offset int) IPriceCatalogDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p priceCatalogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPriceCatalogDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p priceCatalogDo) Unscoped() IPriceCatalogDo {
	return p.withDO(p.DO.Unscoped())
}

func (p priceCatalogDo) Create(values ...*product.PriceCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p priceCatalogDo) CreateInBatches(values []*product.PriceCatalog, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p priceCatalogDo) Save(values ...*product.PriceCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p priceCatalogDo) First() (*product.PriceCatalog, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.PriceCatalog), nil
	}
}

func (p priceCatalogDo) Take() (*product.PriceCatalog, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.PriceCatalog), nil
	}
}

func (p priceCatalogDo) Last() (*product.PriceCatalog, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.PriceCatalog), nil
	}
}

func (p priceCatalogDo) Find() ([]*product.PriceCatalog, error) {
	result, err := p.DO.Find()
	return result.([]*product.PriceCatalog), err
}

func (p priceCatalogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.PriceCatalog, err error) {
	buf := make([]*product.PriceCatalog, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p priceCatalogDo) FindInBatches(result *[]*product.PriceCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p priceCatalogDo) Attrs(attrs ...field.AssignExpr) IPriceCatalogDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p priceCatalogDo) Assign(attrs ...field.AssignExpr) IPriceCatalogDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p priceCatalogDo) Joins(fields ...field.RelationField) IPriceCatalogDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p priceCatalogDo) Preload(fields ...field.RelationField) IPriceCatalogDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p priceCatalogDo) FirstOrInit() (*product.PriceCatalog, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.PriceCatalog), nil
	}
}

func (p priceCatalogDo) FirstOrCreate() (*product.PriceCatalog, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.PriceCatalog), nil
	}
}

func (p priceCatalogDo) FindByPage(offset int, limit int) (result []*product.PriceCatalog, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p priceCatalogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p priceCatalogDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p priceCatalogDo) Delete(models ...*product.PriceCatalog) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *priceCatalogDo) withDO(do gen.Dao) *priceCatalogDo {
	p.DO = *do.(*gen.DO)
	return p
}
