// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/product"
)

func newProductName(db *gorm.DB, opts ...gen.DOOption) productName {
	_productName := productName{}

	_productName.productNameDo.UseDB(db, opts...)
	_productName.productNameDo.UseModel(&product.ProductName{})

	tableName := _productName.productNameDo.TableName()
	_productName.ALL = field.NewAsterisk(tableName)
	_productName.ID = field.NewInt32(tableName, "id")
	_productName.CategoryID = field.NewInt32(tableName, "category_id")
	_productName.Name = field.NewString(tableName, "name")

	_productName.fillFieldMap()

	return _productName
}

type productName struct {
	productNameDo

	ALL        field.Asterisk
	ID         field.Int32
	CategoryID field.Int32
	Name       field.String

	fieldMap map[string]field.Expr
}

func (p productName) Table(newTableName string) *productName {
	p.productNameDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productName) As(alias string) *productName {
	p.productNameDo.DO = *(p.productNameDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productName) updateTableName(table string) *productName {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.CategoryID = field.NewInt32(table, "category_id")
	p.Name = field.NewString(table, "name")

	p.fillFieldMap()

	return p
}

func (p *productName) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productName) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["category_id"] = p.CategoryID
	p.fieldMap["name"] = p.Name
}

func (p productName) clone(db *gorm.DB) productName {
	p.productNameDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productName) replaceDB(db *gorm.DB) productName {
	p.productNameDo.ReplaceDB(db)
	return p
}

type productNameDo struct{ gen.DO }

type IProductNameDo interface {
	gen.SubQuery
	Debug() IProductNameDo
	WithContext(ctx context.Context) IProductNameDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductNameDo
	WriteDB() IProductNameDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductNameDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductNameDo
	Not(conds ...gen.Condition) IProductNameDo
	Or(conds ...gen.Condition) IProductNameDo
	Select(conds ...field.Expr) IProductNameDo
	Where(conds ...gen.Condition) IProductNameDo
	Order(conds ...field.Expr) IProductNameDo
	Distinct(cols ...field.Expr) IProductNameDo
	Omit(cols ...field.Expr) IProductNameDo
	Join(table schema.Tabler, on ...field.Expr) IProductNameDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductNameDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductNameDo
	Group(cols ...field.Expr) IProductNameDo
	Having(conds ...gen.Condition) IProductNameDo
	Limit(limit int) IProductNameDo
	Offset(offset int) IProductNameDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductNameDo
	Unscoped() IProductNameDo
	Create(values ...*product.ProductName) error
	CreateInBatches(values []*product.ProductName, batchSize int) error
	Save(values ...*product.ProductName) error
	First() (*product.ProductName, error)
	Take() (*product.ProductName, error)
	Last() (*product.ProductName, error)
	Find() ([]*product.ProductName, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductName, err error)
	FindInBatches(result *[]*product.ProductName, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductName) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductNameDo
	Assign(attrs ...field.AssignExpr) IProductNameDo
	Joins(fields ...field.RelationField) IProductNameDo
	Preload(fields ...field.RelationField) IProductNameDo
	FirstOrInit() (*product.ProductName, error)
	FirstOrCreate() (*product.ProductName, error)
	FindByPage(offset int, limit int) (result []*product.ProductName, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductNameDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productNameDo) Debug() IProductNameDo {
	return p.withDO(p.DO.Debug())
}

func (p productNameDo) WithContext(ctx context.Context) IProductNameDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productNameDo) ReadDB() IProductNameDo {
	return p.Clauses(dbresolver.Read)
}

func (p productNameDo) WriteDB() IProductNameDo {
	return p.Clauses(dbresolver.Write)
}

func (p productNameDo) Session(config *gorm.Session) IProductNameDo {
	return p.withDO(p.DO.Session(config))
}

func (p productNameDo) Clauses(conds ...clause.Expression) IProductNameDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productNameDo) Returning(value interface{}, columns ...string) IProductNameDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productNameDo) Not(conds ...gen.Condition) IProductNameDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productNameDo) Or(conds ...gen.Condition) IProductNameDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productNameDo) Select(conds ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productNameDo) Where(conds ...gen.Condition) IProductNameDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productNameDo) Order(conds ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productNameDo) Distinct(cols ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productNameDo) Omit(cols ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productNameDo) Join(table schema.Tabler, on ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productNameDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productNameDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productNameDo) Group(cols ...field.Expr) IProductNameDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productNameDo) Having(conds ...gen.Condition) IProductNameDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productNameDo) Limit(limit int) IProductNameDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productNameDo) Offset(offset int) IProductNameDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productNameDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductNameDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productNameDo) Unscoped() IProductNameDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productNameDo) Create(values ...*product.ProductName) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productNameDo) CreateInBatches(values []*product.ProductName, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productNameDo) Save(values ...*product.ProductName) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productNameDo) First() (*product.ProductName, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductName), nil
	}
}

func (p productNameDo) Take() (*product.ProductName, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductName), nil
	}
}

func (p productNameDo) Last() (*product.ProductName, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductName), nil
	}
}

func (p productNameDo) Find() ([]*product.ProductName, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductName), err
}

func (p productNameDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductName, err error) {
	buf := make([]*product.ProductName, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productNameDo) FindInBatches(result *[]*product.ProductName, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productNameDo) Attrs(attrs ...field.AssignExpr) IProductNameDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productNameDo) Assign(attrs ...field.AssignExpr) IProductNameDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productNameDo) Joins(fields ...field.RelationField) IProductNameDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productNameDo) Preload(fields ...field.RelationField) IProductNameDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productNameDo) FirstOrInit() (*product.ProductName, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductName), nil
	}
}

func (p productNameDo) FirstOrCreate() (*product.ProductName, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductName), nil
	}
}

func (p productNameDo) FindByPage(offset int, limit int) (result []*product.ProductName, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productNameDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productNameDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productNameDo) Delete(models ...*product.ProductName) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productNameDo) withDO(do gen.Dao) *productNameDo {
	p.DO = *do.(*gen.DO)
	return p
}
