// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/product"
)

func newShape(db *gorm.DB, opts ...gen.DOOption) shape {
	_shape := shape{}

	_shape.shapeDo.UseDB(db, opts...)
	_shape.shapeDo.UseModel(&product.Shape{})

	tableName := _shape.shapeDo.TableName()
	_shape.ALL = field.NewAsterisk(tableName)
	_shape.ID = field.NewInt32(tableName, "id")
	_shape.Name = field.NewString(tableName, "name")
	_shape.Params = field.NewString(tableName, "params")

	_shape.fillFieldMap()

	return _shape
}

type shape struct {
	shapeDo

	ALL    field.Asterisk
	ID     field.Int32
	Name   field.String
	Params field.String

	fieldMap map[string]field.Expr
}

func (s shape) Table(newTableName string) *shape {
	s.shapeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shape) As(alias string) *shape {
	s.shapeDo.DO = *(s.shapeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shape) updateTableName(table string) *shape {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Name = field.NewString(table, "name")
	s.Params = field.NewString(table, "params")

	s.fillFieldMap()

	return s
}

func (s *shape) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shape) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["params"] = s.Params
}

func (s shape) clone(db *gorm.DB) shape {
	s.shapeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shape) replaceDB(db *gorm.DB) shape {
	s.shapeDo.ReplaceDB(db)
	return s
}

type shapeDo struct{ gen.DO }

type IShapeDo interface {
	gen.SubQuery
	Debug() IShapeDo
	WithContext(ctx context.Context) IShapeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShapeDo
	WriteDB() IShapeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShapeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShapeDo
	Not(conds ...gen.Condition) IShapeDo
	Or(conds ...gen.Condition) IShapeDo
	Select(conds ...field.Expr) IShapeDo
	Where(conds ...gen.Condition) IShapeDo
	Order(conds ...field.Expr) IShapeDo
	Distinct(cols ...field.Expr) IShapeDo
	Omit(cols ...field.Expr) IShapeDo
	Join(table schema.Tabler, on ...field.Expr) IShapeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShapeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShapeDo
	Group(cols ...field.Expr) IShapeDo
	Having(conds ...gen.Condition) IShapeDo
	Limit(limit int) IShapeDo
	Offset(offset int) IShapeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShapeDo
	Unscoped() IShapeDo
	Create(values ...*product.Shape) error
	CreateInBatches(values []*product.Shape, batchSize int) error
	Save(values ...*product.Shape) error
	First() (*product.Shape, error)
	Take() (*product.Shape, error)
	Last() (*product.Shape, error)
	Find() ([]*product.Shape, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.Shape, err error)
	FindInBatches(result *[]*product.Shape, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.Shape) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShapeDo
	Assign(attrs ...field.AssignExpr) IShapeDo
	Joins(fields ...field.RelationField) IShapeDo
	Preload(fields ...field.RelationField) IShapeDo
	FirstOrInit() (*product.Shape, error)
	FirstOrCreate() (*product.Shape, error)
	FindByPage(offset int, limit int) (result []*product.Shape, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShapeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shapeDo) Debug() IShapeDo {
	return s.withDO(s.DO.Debug())
}

func (s shapeDo) WithContext(ctx context.Context) IShapeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shapeDo) ReadDB() IShapeDo {
	return s.Clauses(dbresolver.Read)
}

func (s shapeDo) WriteDB() IShapeDo {
	return s.Clauses(dbresolver.Write)
}

func (s shapeDo) Session(config *gorm.Session) IShapeDo {
	return s.withDO(s.DO.Session(config))
}

func (s shapeDo) Clauses(conds ...clause.Expression) IShapeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shapeDo) Returning(value interface{}, columns ...string) IShapeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shapeDo) Not(conds ...gen.Condition) IShapeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shapeDo) Or(conds ...gen.Condition) IShapeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shapeDo) Select(conds ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shapeDo) Where(conds ...gen.Condition) IShapeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shapeDo) Order(conds ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shapeDo) Distinct(cols ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shapeDo) Omit(cols ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shapeDo) Join(table schema.Tabler, on ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shapeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShapeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shapeDo) RightJoin(table schema.Tabler, on ...field.Expr) IShapeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shapeDo) Group(cols ...field.Expr) IShapeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shapeDo) Having(conds ...gen.Condition) IShapeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shapeDo) Limit(limit int) IShapeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shapeDo) Offset(offset int) IShapeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shapeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShapeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shapeDo) Unscoped() IShapeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shapeDo) Create(values ...*product.Shape) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shapeDo) CreateInBatches(values []*product.Shape, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shapeDo) Save(values ...*product.Shape) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shapeDo) First() (*product.Shape, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.Shape), nil
	}
}

func (s shapeDo) Take() (*product.Shape, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.Shape), nil
	}
}

func (s shapeDo) Last() (*product.Shape, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.Shape), nil
	}
}

func (s shapeDo) Find() ([]*product.Shape, error) {
	result, err := s.DO.Find()
	return result.([]*product.Shape), err
}

func (s shapeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.Shape, err error) {
	buf := make([]*product.Shape, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shapeDo) FindInBatches(result *[]*product.Shape, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shapeDo) Attrs(attrs ...field.AssignExpr) IShapeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shapeDo) Assign(attrs ...field.AssignExpr) IShapeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shapeDo) Joins(fields ...field.RelationField) IShapeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shapeDo) Preload(fields ...field.RelationField) IShapeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shapeDo) FirstOrInit() (*product.Shape, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.Shape), nil
	}
}

func (s shapeDo) FirstOrCreate() (*product.Shape, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.Shape), nil
	}
}

func (s shapeDo) FindByPage(offset int, limit int) (result []*product.Shape, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shapeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shapeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shapeDo) Delete(models ...*product.Shape) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shapeDo) withDO(do gen.Dao) *shapeDo {
	s.DO = *do.(*gen.DO)
	return s
}
