// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/product"
)

func newProductSpec(db *gorm.DB, opts ...gen.DOOption) productSpec {
	_productSpec := productSpec{}

	_productSpec.productSpecDo.UseDB(db, opts...)
	_productSpec.productSpecDo.UseModel(&product.ProductSpec{})

	tableName := _productSpec.productSpecDo.TableName()
	_productSpec.ALL = field.NewAsterisk(tableName)
	_productSpec.ID = field.NewInt32(tableName, "id")
	_productSpec.CategoryID = field.NewInt32(tableName, "category_id")
	_productSpec.ProductNameID = field.NewInt32(tableName, "product_name_id")
	_productSpec.Spec = field.NewString(tableName, "spec")
	_productSpec.HighThreshold = field.NewInt32(tableName, "high_threshold")
	_productSpec.LowThreshold = field.NewInt32(tableName, "low_threshold")
	_productSpec.ShapeID = field.NewInt32(tableName, "shape_id")
	_productSpec.ShapeParams = field.NewString(tableName, "shape_params")
	_productSpec.Density = field.NewFloat64(tableName, "density")
	_productSpec.Weight = field.NewFloat64(tableName, "weight")
	_productSpec.Material = field.NewString(tableName, "material")

	_productSpec.fillFieldMap()

	return _productSpec
}

type productSpec struct {
	productSpecDo

	ALL           field.Asterisk
	ID            field.Int32
	CategoryID    field.Int32
	ProductNameID field.Int32
	Spec          field.String
	HighThreshold field.Int32
	LowThreshold  field.Int32
	ShapeID       field.Int32
	ShapeParams   field.String
	Density       field.Float64
	Weight        field.Float64
	Material      field.String

	fieldMap map[string]field.Expr
}

func (p productSpec) Table(newTableName string) *productSpec {
	p.productSpecDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productSpec) As(alias string) *productSpec {
	p.productSpecDo.DO = *(p.productSpecDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productSpec) updateTableName(table string) *productSpec {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.CategoryID = field.NewInt32(table, "category_id")
	p.ProductNameID = field.NewInt32(table, "product_name_id")
	p.Spec = field.NewString(table, "spec")
	p.HighThreshold = field.NewInt32(table, "high_threshold")
	p.LowThreshold = field.NewInt32(table, "low_threshold")
	p.ShapeID = field.NewInt32(table, "shape_id")
	p.ShapeParams = field.NewString(table, "shape_params")
	p.Density = field.NewFloat64(table, "density")
	p.Weight = field.NewFloat64(table, "weight")
	p.Material = field.NewString(table, "material")

	p.fillFieldMap()

	return p
}

func (p *productSpec) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productSpec) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["category_id"] = p.CategoryID
	p.fieldMap["product_name_id"] = p.ProductNameID
	p.fieldMap["spec"] = p.Spec
	p.fieldMap["high_threshold"] = p.HighThreshold
	p.fieldMap["low_threshold"] = p.LowThreshold
	p.fieldMap["shape_id"] = p.ShapeID
	p.fieldMap["shape_params"] = p.ShapeParams
	p.fieldMap["density"] = p.Density
	p.fieldMap["weight"] = p.Weight
	p.fieldMap["material"] = p.Material
}

func (p productSpec) clone(db *gorm.DB) productSpec {
	p.productSpecDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productSpec) replaceDB(db *gorm.DB) productSpec {
	p.productSpecDo.ReplaceDB(db)
	return p
}

type productSpecDo struct{ gen.DO }

type IProductSpecDo interface {
	gen.SubQuery
	Debug() IProductSpecDo
	WithContext(ctx context.Context) IProductSpecDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductSpecDo
	WriteDB() IProductSpecDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductSpecDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductSpecDo
	Not(conds ...gen.Condition) IProductSpecDo
	Or(conds ...gen.Condition) IProductSpecDo
	Select(conds ...field.Expr) IProductSpecDo
	Where(conds ...gen.Condition) IProductSpecDo
	Order(conds ...field.Expr) IProductSpecDo
	Distinct(cols ...field.Expr) IProductSpecDo
	Omit(cols ...field.Expr) IProductSpecDo
	Join(table schema.Tabler, on ...field.Expr) IProductSpecDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo
	Group(cols ...field.Expr) IProductSpecDo
	Having(conds ...gen.Condition) IProductSpecDo
	Limit(limit int) IProductSpecDo
	Offset(offset int) IProductSpecDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpecDo
	Unscoped() IProductSpecDo
	Create(values ...*product.ProductSpec) error
	CreateInBatches(values []*product.ProductSpec, batchSize int) error
	Save(values ...*product.ProductSpec) error
	First() (*product.ProductSpec, error)
	Take() (*product.ProductSpec, error)
	Last() (*product.ProductSpec, error)
	Find() ([]*product.ProductSpec, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductSpec, err error)
	FindInBatches(result *[]*product.ProductSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductSpec) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductSpecDo
	Assign(attrs ...field.AssignExpr) IProductSpecDo
	Joins(fields ...field.RelationField) IProductSpecDo
	Preload(fields ...field.RelationField) IProductSpecDo
	FirstOrInit() (*product.ProductSpec, error)
	FirstOrCreate() (*product.ProductSpec, error)
	FindByPage(offset int, limit int) (result []*product.ProductSpec, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductSpecDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productSpecDo) Debug() IProductSpecDo {
	return p.withDO(p.DO.Debug())
}

func (p productSpecDo) WithContext(ctx context.Context) IProductSpecDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productSpecDo) ReadDB() IProductSpecDo {
	return p.Clauses(dbresolver.Read)
}

func (p productSpecDo) WriteDB() IProductSpecDo {
	return p.Clauses(dbresolver.Write)
}

func (p productSpecDo) Session(config *gorm.Session) IProductSpecDo {
	return p.withDO(p.DO.Session(config))
}

func (p productSpecDo) Clauses(conds ...clause.Expression) IProductSpecDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productSpecDo) Returning(value interface{}, columns ...string) IProductSpecDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productSpecDo) Not(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productSpecDo) Or(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productSpecDo) Select(conds ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productSpecDo) Where(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productSpecDo) Order(conds ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productSpecDo) Distinct(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productSpecDo) Omit(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productSpecDo) Join(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productSpecDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productSpecDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productSpecDo) Group(cols ...field.Expr) IProductSpecDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productSpecDo) Having(conds ...gen.Condition) IProductSpecDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productSpecDo) Limit(limit int) IProductSpecDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productSpecDo) Offset(offset int) IProductSpecDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productSpecDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpecDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productSpecDo) Unscoped() IProductSpecDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productSpecDo) Create(values ...*product.ProductSpec) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productSpecDo) CreateInBatches(values []*product.ProductSpec, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productSpecDo) Save(values ...*product.ProductSpec) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productSpecDo) First() (*product.ProductSpec, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSpec), nil
	}
}

func (p productSpecDo) Take() (*product.ProductSpec, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSpec), nil
	}
}

func (p productSpecDo) Last() (*product.ProductSpec, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSpec), nil
	}
}

func (p productSpecDo) Find() ([]*product.ProductSpec, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductSpec), err
}

func (p productSpecDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductSpec, err error) {
	buf := make([]*product.ProductSpec, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productSpecDo) FindInBatches(result *[]*product.ProductSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productSpecDo) Attrs(attrs ...field.AssignExpr) IProductSpecDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productSpecDo) Assign(attrs ...field.AssignExpr) IProductSpecDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productSpecDo) Joins(fields ...field.RelationField) IProductSpecDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productSpecDo) Preload(fields ...field.RelationField) IProductSpecDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productSpecDo) FirstOrInit() (*product.ProductSpec, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSpec), nil
	}
}

func (p productSpecDo) FirstOrCreate() (*product.ProductSpec, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSpec), nil
	}
}

func (p productSpecDo) FindByPage(offset int, limit int) (result []*product.ProductSpec, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productSpecDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productSpecDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productSpecDo) Delete(models ...*product.ProductSpec) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productSpecDo) withDO(do gen.Dao) *productSpecDo {
	p.DO = *do.(*gen.DO)
	return p
}
