// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"time"
)

const TableNameAQuoteItem = "A_quote_item"

// AQuoteItem mapped from table <A_quote_item>
type AQuoteItem struct {
	ID                  int32      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteID             *int32     `gorm:"column:quote_id;type:int unsigned" json:"quote_id"`
	ProductCategoryID   *int32     `gorm:"column:product_category_id;type:int unsigned" json:"product_category_id"`
	ProductCategoryName *string    `gorm:"column:product_category_name;type:varchar(255)" json:"product_category_name"`
	ProductNameID       *int32     `gorm:"column:product_name_id;type:int unsigned" json:"product_name_id"`
	ProductName         *string    `gorm:"column:product_name;type:varchar(255)" json:"product_name"`
	SpecificationModel  *string    `gorm:"column:specification_model;type:varchar(255)" json:"specification_model"`
	PriceCatalogVersion *string    `gorm:"column:price_catalog_version;type:varchar(255)" json:"price_catalog_version"`
	OrderBatchTier      *string    `gorm:"column:order_batch_tier;type:varchar(255)" json:"order_batch_tier"`
	CatalogBasePrice    *float64   `gorm:"column:catalog_base_price;type:decimal(10,2)" json:"catalog_base_price"`
	QuoteFloatRate      *float64   `gorm:"column:quote_float_rate;type:decimal(8,4)" json:"quote_float_rate"`
	QuoteUnitPrice      *float64   `gorm:"column:quote_unit_price;type:decimal(10,2)" json:"quote_unit_price"`
	Quantity            *int32     `gorm:"column:quantity;type:int" json:"quantity"`
	TotalAmount         *float64   `gorm:"column:total_amount;type:decimal(10,2) unsigned" json:"total_amount"`
	IsBelowPriceFloor   *bool      `gorm:"column:is_below_price_floor;type:tinyint(1)" json:"is_below_price_floor"`
	CreatedAt           *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt           *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName AQuoteItem's table name
func (*AQuoteItem) TableName() string {
	return TableNameAQuoteItem
}
