// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameBQuoteItem = "B_quote_item"

// BQuoteItem mapped from table <B_quote_item>
type BQuoteItem struct {
	ID                   int32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteID              *int32   `gorm:"column:quote_id;type:int unsigned" json:"quote_id"`
	ProductNameID        *int32   `gorm:"column:product_name_id;type:int unsigned" json:"product_name_id"`
	ProductName          *string  `gorm:"column:product_name;type:varchar(255)" json:"product_name"`
	SpecificationModelID *int32   `gorm:"column:specification_model_id;type:int unsigned" json:"specification_model_id"`
	SpecificationModel   *string  `gorm:"column:specification_model;type:varchar(255)" json:"specification_model"`
	BasePrice            *float64 `gorm:"column:base_price;type:decimal(10,2)" json:"base_price"`
	BatchTier            *string  `gorm:"column:batch_tier;type:varchar(255)" json:"batch_tier"`
	DimensionParams      *string  `gorm:"column:dimension_params;type:json" json:"dimension_params"`
	DimensionFactor      *string  `gorm:"column:dimension_factor;type:varchar(255)" json:"dimension_factor"`
	ProcessParams        *string  `gorm:"column:process_params;type:json" json:"process_params"`
	ProcessFactor        *string  `gorm:"column:process_factor;type:varchar(255)" json:"process_factor"`
	PurityFactor         *string  `gorm:"column:purity_factor;type:varchar(255)" json:"purity_factor"`
	MaterialTotalFactor  *string  `gorm:"column:material_total_factor;type:varchar(255)" json:"material_total_factor"`
	LaborTotalFactor     *string  `gorm:"column:labor_total_factor;type:varchar(255)" json:"labor_total_factor"`
	ManuCostTotalFactor  *string  `gorm:"column:manu_cost_total_factor;type:varchar(255)" json:"manu_cost_total_factor"`
	Material             *string  `gorm:"column:material;type:varchar(255)" json:"material"`
	BaseMaterialCost     *float64 `gorm:"column:base_material_cost;type:decimal(10,2)" json:"base_material_cost"`
	BaseLaborCost        *float64 `gorm:"column:base_labor_cost;type:decimal(10,2)" json:"base_labor_cost"`
	BaseVariOverhead     *float64 `gorm:"column:base_vari_overhead;type:decimal(10,2)" json:"base_vari_overhead"`
	BaseFixedOverhead    *float64 `gorm:"column:base_fixed_overhead;type:decimal(10,2)" json:"base_fixed_overhead"`
	BasePeriodExpense    *float64 `gorm:"column:base_period_expense;type:decimal(10,2)" json:"base_period_expense"`
	BatchFactor          *string  `gorm:"column:batch_factor;type:varchar(255)" json:"batch_factor"`
	FinalBasePrice       *float64 `gorm:"column:final_base_price;type:decimal(10,2)" json:"final_base_price"`
	QuoteUnitPrice       *float64 `gorm:"column:quote_unit_price;type:decimal(10,2)" json:"quote_unit_price"`
	Quantity             *string  `gorm:"column:quantity;type:varchar(255)" json:"quantity"`
}

// TableName BQuoteItem's table name
func (*BQuoteItem) TableName() string {
	return TableNameBQuoteItem
}
