// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameMainCategory = "quote_manage.main_category"

// MainCategory mapped from table <quote_manage.main_category>
type MainCategory struct {
	ID               int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MainCategoryName *string `gorm:"column:main_category_name;type:varchar(255)" json:"main_category_name"`
}

// TableName MainCategory's table name
func (*MainCategory) TableName() string {
	return TableNameMainCategory
}
