// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameQuoteProcessNode = "quote_manage.quote_process_node"

// QuoteProcessNode mapped from table <quote_manage.quote_process_node>
type QuoteProcessNode struct {
	ID                  int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProcessID           *int32  `gorm:"column:process_id;type:int unsigned" json:"process_id"`
	SeqNum              *int32  `gorm:"column:seq_num;type:int" json:"seq_num"`
	Name                *string `gorm:"column:name;type:varchar(255)" json:"name"`
	ApproveEmployeeID   *int32  `gorm:"column:approve_employee_id;type:int unsigned" json:"approve_employee_id"`
	ApproveEmployeeName *string `gorm:"column:approve_employee_name;type:varchar(255)" json:"approve_employee_name"`
	Status              *string `gorm:"column:status;type:varchar(255)" json:"status"`
	ApproveComment      *string `gorm:"column:approve_comment;type:varchar(255)" json:"approve_comment"`
	CreatedAt           *string `gorm:"column:created_at;type:varchar(255)" json:"created_at"`
	ApproveAt           *string `gorm:"column:approve_at;type:varchar(255)" json:"approve_at"`
}

// TableName QuoteProcessNode's table name
func (*QuoteProcessNode) TableName() string {
	return TableNameQuoteProcessNode
}
