// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameProductSpec = "quote_manage.product_spec"

// ProductSpec mapped from table <quote_manage.product_spec>
type ProductSpec struct {
	ID               int32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MainCategory     *string  `gorm:"column:main_category;type:varchar(255)" json:"main_category"`
	ProductName      *string  `gorm:"column:product_name;type:varchar(255)" json:"product_name"`
	Spec             *string  `gorm:"column:spec;type:varchar(255)" json:"spec"`
	HighThreshold    *int32   `gorm:"column:high_threshold;type:int" json:"high_threshold"`
	LowThreshold     *int32   `gorm:"column:low_threshold;type:int" json:"low_threshold"`
	BigBatchPrice    *float64 `gorm:"column:big_batch_price;type:decimal(10,2)" json:"big_batch_price"`
	MiddleBatchPrice *float64 `gorm:"column:middle_batch_price;type:decimal(10,2)" json:"middle_batch_price"`
	SmallBatchPrice  *float64 `gorm:"column:small_batch_price;type:decimal(10,2)" json:"small_batch_price"`
	FloorPrice       *float64 `gorm:"column:floor_price;type:decimal(10,2)" json:"floor_price"`
	IsDeleted        *bool    `gorm:"column:is_deleted;type:tinyint(1)" json:"is_deleted"`
}

// TableName ProductSpec's table name
func (*ProductSpec) TableName() string {
	return TableNameProductSpec
}
