// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameQuoteProcess = "quote_manage.quote_process"

// QuoteProcess mapped from table <quote_manage.quote_process>
type QuoteProcess struct {
	ID                  int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteID             *int32  `gorm:"column:quote_id;type:int unsigned" json:"quote_id"`
	CreateEmployeeID    *int32  `gorm:"column:create_employee_id;type:int unsigned" json:"create_employee_id"`
	CreateEmployeeName  *string `gorm:"column:create_employee_name;type:varchar(255)" json:"create_employee_name"`
	PresentNodeID       *int32  `gorm:"column:present_node_id;type:int unsigned" json:"present_node_id"`
	PresentNodeName     *string `gorm:"column:present_node_name;type:varchar(255)" json:"present_node_name"`
	PresentStatus       *string `gorm:"column:present_status;type:varchar(255)" json:"present_status"`
	PresentApproverID   *int32  `gorm:"column:present_approver_id;type:int" json:"present_approver_id"`
	PresentApproverName *string `gorm:"column:present_approver_name;type:varchar(255)" json:"present_approver_name"`
	CreatedAt           *string `gorm:"column:created_at;type:varchar(255)" json:"created_at"`
}

// TableName QuoteProcess's table name
func (*QuoteProcess) TableName() string {
	return TableNameQuoteProcess
}
