// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"time"
)

const TableNameQuote = "quote_manage.quote"

// Quote mapped from table <quote_manage.quote>
type Quote struct {
	ID                  int32      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteCode           *string    `gorm:"column:quote_code;type:varchar(255)" json:"quote_code"`
	CustomerID          *int32     `gorm:"column:customer_id;type:int unsigned" json:"customer_id"`
	CustomerName        *string    `gorm:"column:customer_name;type:varchar(255)" json:"customer_name"`
	ContactName         *string    `gorm:"column:contact_name;type:varchar(255)" json:"contact_name"`
	ContactTitle        *string    `gorm:"column:contact_title;type:varchar(255)" json:"contact_title"`
	ValidDays           *string    `gorm:"column:valid_days;type:varchar(255)" json:"valid_days"`
	CreatorID           *int32     `gorm:"column:creator_id;type:int unsigned" json:"creator_id"`
	CreatorName         *string    `gorm:"column:creator_name;type:varchar(255)" json:"creator_name"`
	QuoteDate           *time.Time `gorm:"column:quote_date;type:date" json:"quote_date"`
	PayWay              *string    `gorm:"column:pay_way;type:varchar(255)" json:"pay_way"`
	CreditPeriod        *string    `gorm:"column:credit_period;type:varchar(255)" json:"credit_period"`
	Remarks             *string    `gorm:"column:remarks;type:varchar(255)" json:"remarks"`
	AttachmentPathArray *string    `gorm:"column:attachment_path_array;type:json" json:"attachment_path_array"`
}

// TableName Quote's table name
func (*Quote) TableName() string {
	return TableNameQuote
}
