// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameProcessInstance = "quote_manage.process_instance"

// ProcessInstance mapped from table <quote_manage.process_instance>
type ProcessInstance struct {
	ID        int32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteID   *int32 `gorm:"column:quote_id;type:int unsigned" json:"quote_id"`
	ProcessID *int32 `gorm:"column:process_id;type:int unsigned" json:"process_id"`
}

// TableName ProcessInstance's table name
func (*ProcessInstance) TableName() string {
	return TableNameProcessInstance
}
