// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

import (
	"time"
)

const TableNameQuoteProcess = "quote_manage.quote_process"

// QuoteProcess mapped from table <quote_manage.quote_process>
type QuoteProcess struct {
	ID                  int32      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	QuoteID             *int32     `gorm:"column:quote_id;type:int unsigned" json:"quote_id"`
	CreatorID           *int32     `gorm:"column:creator_id;type:int unsigned" json:"creator_id"`
	CreatorName         *string    `gorm:"column:creator_name;type:varchar(255)" json:"creator_name"`
	PresentStatus       *string    `gorm:"column:present_status;type:varchar(255)" json:"present_status"`
	PresentSeqNum       *int32     `gorm:"column:present_seq_num;type:int" json:"present_seq_num"`
	PresentNodeNum      *int32     `gorm:"column:present_node_num;type:int" json:"present_node_num"`
	PresentNodeID       *int32     `gorm:"column:present_node_id;type:int unsigned" json:"present_node_id"`
	PresentNodeName     *string    `gorm:"column:present_node_name;type:varchar(255)" json:"present_node_name"`
	PresentApproverID   *int32     `gorm:"column:present_approver_id;type:int" json:"present_approver_id"`
	PresentApproverName *string    `gorm:"column:present_approver_name;type:varchar(255)" json:"present_approver_name"`
	CreatedAt           *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt           *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName QuoteProcess's table name
func (*QuoteProcess) TableName() string {
	return TableNameQuoteProcess
}
