// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package quote_manage

const TableNameCostWorksheet = "quote_manage.cost_worksheet"

// CostWorksheet mapped from table <quote_manage.cost_worksheet>
type CostWorksheet struct {
	ID                  int32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	SpecID              *int32   `gorm:"column:spec_id;type:int unsigned;index:cost_worksheet_spec,priority:1" json:"spec_id"`
	MaterialCost        *float64 `gorm:"column:material_cost;type:decimal(10,2)" json:"material_cost"`
	LaborCost           *float64 `gorm:"column:labor_cost;type:decimal(10,2)" json:"labor_cost"`
	VariOverhead        *float64 `gorm:"column:vari_overhead;type:decimal(10,2)" json:"vari_overhead"`
	FixedOverhead       *float64 `gorm:"column:fixed_overhead;type:decimal(10,2)" json:"fixed_overhead"`
	FixedOverheadTiered *float64 `gorm:"column:fixed_overhead_tiered;type:decimal(10,2)" json:"fixed_overhead_tiered"`
	PeriodExpense       *float64 `gorm:"column:period_expense;type:decimal(10,2)" json:"period_expense"`
	TargetProfitRate    *float64 `gorm:"column:target_profit_rate;type:decimal(8,4)" json:"target_profit_rate"`
	TargetProfit        *float64 `gorm:"column:target_profit;type:decimal(10,2)" json:"target_profit"`
	VatAmount           *float64 `gorm:"column:vat_amount;type:decimal(10,2)" json:"vat_amount"`
}

// TableName CostWorksheet's table name
func (*CostWorksheet) TableName() string {
	return TableNameCostWorksheet
}
