// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNamePriceCatalog = "price_catalog"

// PriceCatalog mapped from table <price_catalog>
type PriceCatalog struct {
	ID    int32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	SkuID *int32   `gorm:"column:sku_id;type:int" json:"sku_id"`
	Price *float64 `gorm:"column:price;type:decimal(10,2)" json:"price"`
}

// TableName PriceCatalog's table name
func (*PriceCatalog) TableName() string {
	return TableNamePriceCatalog
}
