// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameProductSpec = "product.product_spec"

// ProductSpec mapped from table <product.product_spec>
type ProductSpec struct {
	ID            int32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	CategoryID    *int32   `gorm:"column:category_id;type:int unsigned;index:spec_category,priority:1" json:"category_id"`
	ProductNameID *int32   `gorm:"column:product_name_id;type:int unsigned;index:spec_product_name,priority:1" json:"product_name_id"`
	Spec          *string  `gorm:"column:spec;type:varchar(255)" json:"spec"`
	HighThreshold *int32   `gorm:"column:high_threshold;type:int" json:"high_threshold"`
	LowThreshold  *int32   `gorm:"column:low_threshold;type:int" json:"low_threshold"`
	ShapeID       *int32   `gorm:"column:shape_id;type:int unsigned;index:spec_shape,priority:1" json:"shape_id"`
	ShapeParams   *string  `gorm:"column:shape_params;type:json" json:"shape_params"`
	Density       *float64 `gorm:"column:density;type:decimal(10,2)" json:"density"`
	Weight        *float64 `gorm:"column:weight;type:double" json:"weight"`
	Material      *string  `gorm:"column:material;type:varchar(255)" json:"material"`
}

// TableName ProductSpec's table name
func (*ProductSpec) TableName() string {
	return TableNameProductSpec
}
