// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameProductName = "product_name"

// ProductName mapped from table <product_name>
type ProductName struct {
	ID         int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	CategoryID *int32  `gorm:"column:category_id;type:int unsigned;index:category,priority:1" json:"category_id"`
	Name       *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName ProductName's table name
func (*ProductName) TableName() string {
	return TableNameProductName
}
