// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameProductSku = "product_sku"

// ProductSku mapped from table <product_sku>
type ProductSku struct {
	ID     int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	SpuID  *int32  `gorm:"column:spu_id;type:int unsigned" json:"spu_id"`
	ItemID *int32  `gorm:"column:item_id;type:int" json:"item_id"`
	Name   *string `gorm:"column:name;type:varchar(255)" json:"name"`
	Spec   *string `gorm:"column:spec;type:varchar(255)" json:"spec"`
}

// TableName ProductSku's table name
func (*ProductSku) TableName() string {
	return TableNameProductSku
}
