// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameProductCategory = "product_category"

// ProductCategory mapped from table <product_category>
type ProductCategory struct {
	ID   int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName ProductCategory's table name
func (*ProductCategory) TableName() string {
	return TableNameProductCategory
}
