// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameProductSpu = "product_spu"

// ProductSpu mapped from table <product_spu>
type ProductSpu struct {
	ID         int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	CategoryID *int32  `gorm:"column:category_id;type:int unsigned" json:"category_id"`
	Name       *string `gorm:"column:name;type:varchar(255)" json:"name"`
}

// TableName ProductSpu's table name
func (*ProductSpu) TableName() string {
	return TableNameProductSpu
}
