// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

const TableNameShape = "shape"

// Shape mapped from table <shape>
type Shape struct {
	ID     int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name   *string `gorm:"column:name;type:varchar(255)" json:"name"`
	Params *string `gorm:"column:params;type:json" json:"params"`
}

// TableName Shape's table name
func (*Shape) TableName() string {
	return TableNameShape
}
