// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/general"
)

func newTableRegistry(db *gorm.DB, opts ...gen.DOOption) tableRegistry {
	_tableRegistry := tableRegistry{}

	_tableRegistry.tableRegistryDo.UseDB(db, opts...)
	_tableRegistry.tableRegistryDo.UseModel(&general.TableRegistry{})

	tableName := _tableRegistry.tableRegistryDo.TableName()
	_tableRegistry.ALL = field.NewAsterisk(tableName)
	_tableRegistry.ID = field.NewInt32(tableName, "id")
	_tableRegistry.TableName_ = field.NewString(tableName, "table_name")
	_tableRegistry.DatabaseName = field.NewString(tableName, "database_name")

	_tableRegistry.fillFieldMap()

	return _tableRegistry
}

type tableRegistry struct {
	tableRegistryDo

	ALL          field.Asterisk
	ID           field.Int32
	TableName_   field.String
	DatabaseName field.String

	fieldMap map[string]field.Expr
}

func (t tableRegistry) Table(newTableName string) *tableRegistry {
	t.tableRegistryDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tableRegistry) As(alias string) *tableRegistry {
	t.tableRegistryDo.DO = *(t.tableRegistryDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tableRegistry) updateTableName(table string) *tableRegistry {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.TableName_ = field.NewString(table, "table_name")
	t.DatabaseName = field.NewString(table, "database_name")

	t.fillFieldMap()

	return t
}

func (t *tableRegistry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tableRegistry) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["id"] = t.ID
	t.fieldMap["table_name"] = t.TableName_
	t.fieldMap["database_name"] = t.DatabaseName
}

func (t tableRegistry) clone(db *gorm.DB) tableRegistry {
	t.tableRegistryDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tableRegistry) replaceDB(db *gorm.DB) tableRegistry {
	t.tableRegistryDo.ReplaceDB(db)
	return t
}

type tableRegistryDo struct{ gen.DO }

type ITableRegistryDo interface {
	gen.SubQuery
	Debug() ITableRegistryDo
	WithContext(ctx context.Context) ITableRegistryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITableRegistryDo
	WriteDB() ITableRegistryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITableRegistryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITableRegistryDo
	Not(conds ...gen.Condition) ITableRegistryDo
	Or(conds ...gen.Condition) ITableRegistryDo
	Select(conds ...field.Expr) ITableRegistryDo
	Where(conds ...gen.Condition) ITableRegistryDo
	Order(conds ...field.Expr) ITableRegistryDo
	Distinct(cols ...field.Expr) ITableRegistryDo
	Omit(cols ...field.Expr) ITableRegistryDo
	Join(table schema.Tabler, on ...field.Expr) ITableRegistryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITableRegistryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITableRegistryDo
	Group(cols ...field.Expr) ITableRegistryDo
	Having(conds ...gen.Condition) ITableRegistryDo
	Limit(limit int) ITableRegistryDo
	Offset(offset int) ITableRegistryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITableRegistryDo
	Unscoped() ITableRegistryDo
	Create(values ...*general.TableRegistry) error
	CreateInBatches(values []*general.TableRegistry, batchSize int) error
	Save(values ...*general.TableRegistry) error
	First() (*general.TableRegistry, error)
	Take() (*general.TableRegistry, error)
	Last() (*general.TableRegistry, error)
	Find() ([]*general.TableRegistry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.TableRegistry, err error)
	FindInBatches(result *[]*general.TableRegistry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*general.TableRegistry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITableRegistryDo
	Assign(attrs ...field.AssignExpr) ITableRegistryDo
	Joins(fields ...field.RelationField) ITableRegistryDo
	Preload(fields ...field.RelationField) ITableRegistryDo
	FirstOrInit() (*general.TableRegistry, error)
	FirstOrCreate() (*general.TableRegistry, error)
	FindByPage(offset int, limit int) (result []*general.TableRegistry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITableRegistryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tableRegistryDo) Debug() ITableRegistryDo {
	return t.withDO(t.DO.Debug())
}

func (t tableRegistryDo) WithContext(ctx context.Context) ITableRegistryDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tableRegistryDo) ReadDB() ITableRegistryDo {
	return t.Clauses(dbresolver.Read)
}

func (t tableRegistryDo) WriteDB() ITableRegistryDo {
	return t.Clauses(dbresolver.Write)
}

func (t tableRegistryDo) Session(config *gorm.Session) ITableRegistryDo {
	return t.withDO(t.DO.Session(config))
}

func (t tableRegistryDo) Clauses(conds ...clause.Expression) ITableRegistryDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tableRegistryDo) Returning(value interface{}, columns ...string) ITableRegistryDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tableRegistryDo) Not(conds ...gen.Condition) ITableRegistryDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tableRegistryDo) Or(conds ...gen.Condition) ITableRegistryDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tableRegistryDo) Select(conds ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tableRegistryDo) Where(conds ...gen.Condition) ITableRegistryDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tableRegistryDo) Order(conds ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tableRegistryDo) Distinct(cols ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tableRegistryDo) Omit(cols ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tableRegistryDo) Join(table schema.Tabler, on ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tableRegistryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tableRegistryDo) RightJoin(table schema.Tabler, on ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tableRegistryDo) Group(cols ...field.Expr) ITableRegistryDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tableRegistryDo) Having(conds ...gen.Condition) ITableRegistryDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tableRegistryDo) Limit(limit int) ITableRegistryDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tableRegistryDo) Offset(offset int) ITableRegistryDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tableRegistryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITableRegistryDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tableRegistryDo) Unscoped() ITableRegistryDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tableRegistryDo) Create(values ...*general.TableRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tableRegistryDo) CreateInBatches(values []*general.TableRegistry, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tableRegistryDo) Save(values ...*general.TableRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tableRegistryDo) First() (*general.TableRegistry, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*general.TableRegistry), nil
	}
}

func (t tableRegistryDo) Take() (*general.TableRegistry, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*general.TableRegistry), nil
	}
}

func (t tableRegistryDo) Last() (*general.TableRegistry, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*general.TableRegistry), nil
	}
}

func (t tableRegistryDo) Find() ([]*general.TableRegistry, error) {
	result, err := t.DO.Find()
	return result.([]*general.TableRegistry), err
}

func (t tableRegistryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.TableRegistry, err error) {
	buf := make([]*general.TableRegistry, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tableRegistryDo) FindInBatches(result *[]*general.TableRegistry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tableRegistryDo) Attrs(attrs ...field.AssignExpr) ITableRegistryDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tableRegistryDo) Assign(attrs ...field.AssignExpr) ITableRegistryDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tableRegistryDo) Joins(fields ...field.RelationField) ITableRegistryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tableRegistryDo) Preload(fields ...field.RelationField) ITableRegistryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tableRegistryDo) FirstOrInit() (*general.TableRegistry, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*general.TableRegistry), nil
	}
}

func (t tableRegistryDo) FirstOrCreate() (*general.TableRegistry, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*general.TableRegistry), nil
	}
}

func (t tableRegistryDo) FindByPage(offset int, limit int) (result []*general.TableRegistry, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tableRegistryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tableRegistryDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tableRegistryDo) Delete(models ...*general.TableRegistry) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tableRegistryDo) withDO(do gen.Dao) *tableRegistryDo {
	t.DO = *do.(*gen.DO)
	return t
}
