// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/general"
)

func newProcessEdge(db *gorm.DB, opts ...gen.DOOption) processEdge {
	_processEdge := processEdge{}

	_processEdge.processEdgeDo.UseDB(db, opts...)
	_processEdge.processEdgeDo.UseModel(&general.ProcessEdge{})

	tableName := _processEdge.processEdgeDo.TableName()
	_processEdge.ALL = field.NewAsterisk(tableName)
	_processEdge.ID = field.NewInt32(tableName, "id")
	_processEdge.ProcessID = field.NewInt32(tableName, "process_id")
	_processEdge.ProcessName = field.NewString(tableName, "process_name")
	_processEdge.Type = field.NewString(tableName, "type")
	_processEdge.StartNodeNum = field.NewInt32(tableName, "start_node_num")
	_processEdge.StartNodeName = field.NewString(tableName, "start_node_name")
	_processEdge.EndNodeNum = field.NewInt32(tableName, "end_node_num")
	_processEdge.EndNodeName = field.NewString(tableName, "end_node_name")
	_processEdge.ConditionExpr = field.NewString(tableName, "condition_expr")

	_processEdge.fillFieldMap()

	return _processEdge
}

type processEdge struct {
	processEdgeDo

	ALL           field.Asterisk
	ID            field.Int32
	ProcessID     field.Int32
	ProcessName   field.String
	Type          field.String
	StartNodeNum  field.Int32
	StartNodeName field.String
	EndNodeNum    field.Int32
	EndNodeName   field.String
	ConditionExpr field.String

	fieldMap map[string]field.Expr
}

func (p processEdge) Table(newTableName string) *processEdge {
	p.processEdgeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processEdge) As(alias string) *processEdge {
	p.processEdgeDo.DO = *(p.processEdgeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processEdge) updateTableName(table string) *processEdge {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.ProcessID = field.NewInt32(table, "process_id")
	p.ProcessName = field.NewString(table, "process_name")
	p.Type = field.NewString(table, "type")
	p.StartNodeNum = field.NewInt32(table, "start_node_num")
	p.StartNodeName = field.NewString(table, "start_node_name")
	p.EndNodeNum = field.NewInt32(table, "end_node_num")
	p.EndNodeName = field.NewString(table, "end_node_name")
	p.ConditionExpr = field.NewString(table, "condition_expr")

	p.fillFieldMap()

	return p
}

func (p *processEdge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processEdge) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["process_id"] = p.ProcessID
	p.fieldMap["process_name"] = p.ProcessName
	p.fieldMap["type"] = p.Type
	p.fieldMap["start_node_num"] = p.StartNodeNum
	p.fieldMap["start_node_name"] = p.StartNodeName
	p.fieldMap["end_node_num"] = p.EndNodeNum
	p.fieldMap["end_node_name"] = p.EndNodeName
	p.fieldMap["condition_expr"] = p.ConditionExpr
}

func (p processEdge) clone(db *gorm.DB) processEdge {
	p.processEdgeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processEdge) replaceDB(db *gorm.DB) processEdge {
	p.processEdgeDo.ReplaceDB(db)
	return p
}

type processEdgeDo struct{ gen.DO }

type IProcessEdgeDo interface {
	gen.SubQuery
	Debug() IProcessEdgeDo
	WithContext(ctx context.Context) IProcessEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProcessEdgeDo
	WriteDB() IProcessEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProcessEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProcessEdgeDo
	Not(conds ...gen.Condition) IProcessEdgeDo
	Or(conds ...gen.Condition) IProcessEdgeDo
	Select(conds ...field.Expr) IProcessEdgeDo
	Where(conds ...gen.Condition) IProcessEdgeDo
	Order(conds ...field.Expr) IProcessEdgeDo
	Distinct(cols ...field.Expr) IProcessEdgeDo
	Omit(cols ...field.Expr) IProcessEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IProcessEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProcessEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProcessEdgeDo
	Group(cols ...field.Expr) IProcessEdgeDo
	Having(conds ...gen.Condition) IProcessEdgeDo
	Limit(limit int) IProcessEdgeDo
	Offset(offset int) IProcessEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessEdgeDo
	Unscoped() IProcessEdgeDo
	Create(values ...*general.ProcessEdge) error
	CreateInBatches(values []*general.ProcessEdge, batchSize int) error
	Save(values ...*general.ProcessEdge) error
	First() (*general.ProcessEdge, error)
	Take() (*general.ProcessEdge, error)
	Last() (*general.ProcessEdge, error)
	Find() ([]*general.ProcessEdge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.ProcessEdge, err error)
	FindInBatches(result *[]*general.ProcessEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*general.ProcessEdge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProcessEdgeDo
	Assign(attrs ...field.AssignExpr) IProcessEdgeDo
	Joins(fields ...field.RelationField) IProcessEdgeDo
	Preload(fields ...field.RelationField) IProcessEdgeDo
	FirstOrInit() (*general.ProcessEdge, error)
	FirstOrCreate() (*general.ProcessEdge, error)
	FindByPage(offset int, limit int) (result []*general.ProcessEdge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProcessEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p processEdgeDo) Debug() IProcessEdgeDo {
	return p.withDO(p.DO.Debug())
}

func (p processEdgeDo) WithContext(ctx context.Context) IProcessEdgeDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processEdgeDo) ReadDB() IProcessEdgeDo {
	return p.Clauses(dbresolver.Read)
}

func (p processEdgeDo) WriteDB() IProcessEdgeDo {
	return p.Clauses(dbresolver.Write)
}

func (p processEdgeDo) Session(config *gorm.Session) IProcessEdgeDo {
	return p.withDO(p.DO.Session(config))
}

func (p processEdgeDo) Clauses(conds ...clause.Expression) IProcessEdgeDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processEdgeDo) Returning(value interface{}, columns ...string) IProcessEdgeDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processEdgeDo) Not(conds ...gen.Condition) IProcessEdgeDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processEdgeDo) Or(conds ...gen.Condition) IProcessEdgeDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processEdgeDo) Select(conds ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processEdgeDo) Where(conds ...gen.Condition) IProcessEdgeDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processEdgeDo) Order(conds ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processEdgeDo) Distinct(cols ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processEdgeDo) Omit(cols ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processEdgeDo) Join(table schema.Tabler, on ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processEdgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processEdgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processEdgeDo) Group(cols ...field.Expr) IProcessEdgeDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processEdgeDo) Having(conds ...gen.Condition) IProcessEdgeDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processEdgeDo) Limit(limit int) IProcessEdgeDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processEdgeDo) Offset(offset int) IProcessEdgeDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processEdgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessEdgeDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processEdgeDo) Unscoped() IProcessEdgeDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processEdgeDo) Create(values ...*general.ProcessEdge) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processEdgeDo) CreateInBatches(values []*general.ProcessEdge, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processEdgeDo) Save(values ...*general.ProcessEdge) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processEdgeDo) First() (*general.ProcessEdge, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessEdge), nil
	}
}

func (p processEdgeDo) Take() (*general.ProcessEdge, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessEdge), nil
	}
}

func (p processEdgeDo) Last() (*general.ProcessEdge, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessEdge), nil
	}
}

func (p processEdgeDo) Find() ([]*general.ProcessEdge, error) {
	result, err := p.DO.Find()
	return result.([]*general.ProcessEdge), err
}

func (p processEdgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.ProcessEdge, err error) {
	buf := make([]*general.ProcessEdge, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processEdgeDo) FindInBatches(result *[]*general.ProcessEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processEdgeDo) Attrs(attrs ...field.AssignExpr) IProcessEdgeDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processEdgeDo) Assign(attrs ...field.AssignExpr) IProcessEdgeDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processEdgeDo) Joins(fields ...field.RelationField) IProcessEdgeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processEdgeDo) Preload(fields ...field.RelationField) IProcessEdgeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processEdgeDo) FirstOrInit() (*general.ProcessEdge, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessEdge), nil
	}
}

func (p processEdgeDo) FirstOrCreate() (*general.ProcessEdge, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessEdge), nil
	}
}

func (p processEdgeDo) FindByPage(offset int, limit int) (result []*general.ProcessEdge, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processEdgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processEdgeDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processEdgeDo) Delete(models ...*general.ProcessEdge) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processEdgeDo) withDO(do gen.Dao) *processEdgeDo {
	p.DO = *do.(*gen.DO)
	return p
}
