// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package general

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"csun_server-backend/dao/model/general"
)

func newProcessNode(db *gorm.DB, opts ...gen.DOOption) processNode {
	_processNode := processNode{}

	_processNode.processNodeDo.UseDB(db, opts...)
	_processNode.processNodeDo.UseModel(&general.ProcessNode{})

	tableName := _processNode.processNodeDo.TableName()
	_processNode.ALL = field.NewAsterisk(tableName)
	_processNode.ID = field.NewInt32(tableName, "id")
	_processNode.ProcessID = field.NewInt32(tableName, "process_id")
	_processNode.Name = field.NewString(tableName, "name")

	_processNode.fillFieldMap()

	return _processNode
}

type processNode struct {
	processNodeDo

	ALL       field.Asterisk
	ID        field.Int32
	ProcessID field.Int32
	Name      field.String

	fieldMap map[string]field.Expr
}

func (p processNode) Table(newTableName string) *processNode {
	p.processNodeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processNode) As(alias string) *processNode {
	p.processNodeDo.DO = *(p.processNodeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processNode) updateTableName(table string) *processNode {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.ProcessID = field.NewInt32(table, "process_id")
	p.Name = field.NewString(table, "name")

	p.fillFieldMap()

	return p
}

func (p *processNode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processNode) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["process_id"] = p.ProcessID
	p.fieldMap["name"] = p.Name
}

func (p processNode) clone(db *gorm.DB) processNode {
	p.processNodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processNode) replaceDB(db *gorm.DB) processNode {
	p.processNodeDo.ReplaceDB(db)
	return p
}

type processNodeDo struct{ gen.DO }

type IProcessNodeDo interface {
	gen.SubQuery
	Debug() IProcessNodeDo
	WithContext(ctx context.Context) IProcessNodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProcessNodeDo
	WriteDB() IProcessNodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProcessNodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProcessNodeDo
	Not(conds ...gen.Condition) IProcessNodeDo
	Or(conds ...gen.Condition) IProcessNodeDo
	Select(conds ...field.Expr) IProcessNodeDo
	Where(conds ...gen.Condition) IProcessNodeDo
	Order(conds ...field.Expr) IProcessNodeDo
	Distinct(cols ...field.Expr) IProcessNodeDo
	Omit(cols ...field.Expr) IProcessNodeDo
	Join(table schema.Tabler, on ...field.Expr) IProcessNodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProcessNodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProcessNodeDo
	Group(cols ...field.Expr) IProcessNodeDo
	Having(conds ...gen.Condition) IProcessNodeDo
	Limit(limit int) IProcessNodeDo
	Offset(offset int) IProcessNodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessNodeDo
	Unscoped() IProcessNodeDo
	Create(values ...*general.ProcessNode) error
	CreateInBatches(values []*general.ProcessNode, batchSize int) error
	Save(values ...*general.ProcessNode) error
	First() (*general.ProcessNode, error)
	Take() (*general.ProcessNode, error)
	Last() (*general.ProcessNode, error)
	Find() ([]*general.ProcessNode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.ProcessNode, err error)
	FindInBatches(result *[]*general.ProcessNode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*general.ProcessNode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProcessNodeDo
	Assign(attrs ...field.AssignExpr) IProcessNodeDo
	Joins(fields ...field.RelationField) IProcessNodeDo
	Preload(fields ...field.RelationField) IProcessNodeDo
	FirstOrInit() (*general.ProcessNode, error)
	FirstOrCreate() (*general.ProcessNode, error)
	FindByPage(offset int, limit int) (result []*general.ProcessNode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProcessNodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p processNodeDo) Debug() IProcessNodeDo {
	return p.withDO(p.DO.Debug())
}

func (p processNodeDo) WithContext(ctx context.Context) IProcessNodeDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processNodeDo) ReadDB() IProcessNodeDo {
	return p.Clauses(dbresolver.Read)
}

func (p processNodeDo) WriteDB() IProcessNodeDo {
	return p.Clauses(dbresolver.Write)
}

func (p processNodeDo) Session(config *gorm.Session) IProcessNodeDo {
	return p.withDO(p.DO.Session(config))
}

func (p processNodeDo) Clauses(conds ...clause.Expression) IProcessNodeDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processNodeDo) Returning(value interface{}, columns ...string) IProcessNodeDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processNodeDo) Not(conds ...gen.Condition) IProcessNodeDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processNodeDo) Or(conds ...gen.Condition) IProcessNodeDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processNodeDo) Select(conds ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processNodeDo) Where(conds ...gen.Condition) IProcessNodeDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processNodeDo) Order(conds ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processNodeDo) Distinct(cols ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processNodeDo) Omit(cols ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processNodeDo) Join(table schema.Tabler, on ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processNodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processNodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processNodeDo) Group(cols ...field.Expr) IProcessNodeDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processNodeDo) Having(conds ...gen.Condition) IProcessNodeDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processNodeDo) Limit(limit int) IProcessNodeDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processNodeDo) Offset(offset int) IProcessNodeDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processNodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessNodeDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processNodeDo) Unscoped() IProcessNodeDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processNodeDo) Create(values ...*general.ProcessNode) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processNodeDo) CreateInBatches(values []*general.ProcessNode, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processNodeDo) Save(values ...*general.ProcessNode) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processNodeDo) First() (*general.ProcessNode, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessNode), nil
	}
}

func (p processNodeDo) Take() (*general.ProcessNode, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessNode), nil
	}
}

func (p processNodeDo) Last() (*general.ProcessNode, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessNode), nil
	}
}

func (p processNodeDo) Find() ([]*general.ProcessNode, error) {
	result, err := p.DO.Find()
	return result.([]*general.ProcessNode), err
}

func (p processNodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*general.ProcessNode, err error) {
	buf := make([]*general.ProcessNode, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processNodeDo) FindInBatches(result *[]*general.ProcessNode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processNodeDo) Attrs(attrs ...field.AssignExpr) IProcessNodeDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processNodeDo) Assign(attrs ...field.AssignExpr) IProcessNodeDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processNodeDo) Joins(fields ...field.RelationField) IProcessNodeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processNodeDo) Preload(fields ...field.RelationField) IProcessNodeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processNodeDo) FirstOrInit() (*general.ProcessNode, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessNode), nil
	}
}

func (p processNodeDo) FirstOrCreate() (*general.ProcessNode, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*general.ProcessNode), nil
	}
}

func (p processNodeDo) FindByPage(offset int, limit int) (result []*general.ProcessNode, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processNodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processNodeDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processNodeDo) Delete(models ...*general.ProcessNode) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processNodeDo) withDO(do gen.Dao) *processNodeDo {
	p.DO = *do.(*gen.DO)
	return p
}
