// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package other

const TableNameValueLabel = "other.value_label"

// ValueLabel mapped from table <other.value_label>
type ValueLabel struct {
	ID    int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Value *string `gorm:"column:value;type:varchar(255)" json:"value"`
	Label *string `gorm:"column:label;type:varchar(255)" json:"label"`
}

// TableName ValueLabel's table name
func (*ValueLabel) TableName() string {
	return TableNameValueLabel
}
