// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package other

const TableNameQuantityUnit = "quantity_unit"

// QuantityUnit mapped from table <quantity_unit>
type QuantityUnit struct {
	ID       int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Quantity *string `gorm:"column:quantity;type:varchar(255)" json:"quantity"`
	Unit     *string `gorm:"column:unit;type:varchar(255)" json:"unit"`
}

// TableName QuantityUnit's table name
func (*QuantityUnit) TableName() string {
	return TableNameQuantityUnit
}
